(() => {
'use strict';
const $=id=>document.getElementById(id),M=TriangleMath,canvas=$('scene'),ctx=canvas.getContext('2d');
const colors=['#80c4b2','#e1b27c','#7eb4d3','#c7a5ca','#c4ce94','#f1c6b2'];
let all,data,geometry,net,patch=[],slide=0,progress=0,selected=0,seamIndex=0,zoom=1,pan=[0,0],drag=null,anim=0,width=700,height=500,wordPath=[],wordMatrices=[],loadToken=0;
const fmt=n=>n.toLocaleString('en-US'),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groupName=s=>s.replace(/A4/g,'A₄').replace(/A5/g,'A₅').replace(/A6/g,'A₆').replace(/S4/g,'S₄').replace(/C6/g,'C₆').replace(/M11/g,'M₁₁');
const faceColor=f=>f%2?'#315761':'#84c2b3',seamColor=e=>colors[e%colors.length];
const cycles=a=>a.length?a.map(c=>'('+c.join(' ')+')').join(''):'1';
function screen(v){const R=Math.min(width,height)*.445*zoom;return [width/2+pan[0]+v[0]*R,height/2+pan[1]-v[1]*R];}
function projected(v){return M.project(v,geometry.k);}
function curve(a,b,n=6){const out=[];for(let j=0;j<=n;j++){const t=j/n;out.push(projected(M.norm(a.map((v,i)=>v*(1-t)+b[i]*t),geometry.k)));}return out;}
function sourcePatch(){
 const queue=[{matrix:M.I(),face:0,d:geometry.k===1?-1:0}],seen=new Set(['0,0,100000']),out=[];
 while(queue.length&&out.length<1000){let k=0;for(let j=1;j<queue.length;j++)if(queue[j].d<queue[k].d)k=j;const a=queue.splice(k,1)[0];a.vertices=geometry.vertices.map(v=>M.mv(a.matrix,v));out.push(a);
  for(let side=0;side<3;side++){const matrix=M.mul(a.matrix,geometry.mirrors[side]),c=M.mv(matrix,geometry.center);if(!c.every(Number.isFinite))continue;const key=c.map(v=>Math.round(v*1e5)).join(',');if(seen.has(key))continue;seen.add(key);const p=projected(c),r=p[0]*p[0]+p[1]*p[1];if(geometry.k===-1&&(c[2]<0||r>.993*.993))continue;if(geometry.k===0&&r>8)continue;queue.push({matrix,face:data.neighbors[a.face][side],d:geometry.k===1?-c[2]:r});}
 }
 return out;
}
function trianglePoints(f){return net.corners[f].map(k=>net.positions[k]);}
function centroid(f){const v=trianglePoints(f);return [(v[0][0]+v[1][0]+v[2][0])/3,(v[0][1]+v[1][1]+v[2][1])/3];}
function polygon(points,fill,stroke,line=0.5){if(!points.length)return;ctx.beginPath();points.forEach((v,i)=>{const p=screen(v);if(i)ctx.lineTo(...p);else ctx.moveTo(...p);});ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=line;ctx.stroke();}}
function segment(a,b,color,line=1,dashed=false){ctx.beginPath();ctx.moveTo(...screen(a));ctx.lineTo(...screen(b));ctx.strokeStyle=color;ctx.lineWidth=line;ctx.setLineDash(dashed?[4,4]:[]);ctx.stroke();ctx.setLineDash([]);}
function pathLine(points,color,line=2,dashed=false){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...screen(p)):ctx.moveTo(...screen(p)));ctx.strokeStyle=color;ctx.lineWidth=line;ctx.setLineDash(dashed?[5,4]:[]);ctx.stroke();ctx.setLineDash([]);}
function draw(){
 if(!data||!net)return;const dpr=Math.min(2,devicePixelRatio||1);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle='#102b32';ctx.fillRect(0,0,width,height);ctx.save();ctx.beginPath();ctx.rect(0,0,width,height);ctx.clip();
 const t=progress,e=t*t*(3-2*t);
 // Every target triangle belongs to the exact quotient complex. Geometry is a cut-open layout.
 if(t>.12){ctx.globalAlpha=Math.min(1,(t-.12)/.55);for(let f=0;f<data.counts.triangles;f++)polygon(trianglePoints(f),faceColor(f),t>.6?'#16363c':null,data.order>500?.15:.45);ctx.globalAlpha=1;}
 if(t<.999){
  const clipDisc=geometry.k!==0&&t<.01;if(clipDisc){const [cx,cy]=screen([0,0]);ctx.save();ctx.beginPath();ctx.arc(cx,cy,Math.min(width,height)*.445*zoom,0,2*Math.PI);ctx.clip();}
  for(const cell of patch){const dest=trianglePoints(cell.face),fade=1-Math.max(0,(t-.7)/.3),fill=cell.face===selected?'#e5b77f':faceColor(cell.face);
   const sampled=nodes=>{const pts=[];for(let s=0;s<nodes.length;s++){const a=nodes[s],b=nodes[(s+1)%nodes.length],path=curve(a.v,b.v,geometry.k?5:1);for(let j=0;j<path.length;j++){const u=j/(path.length-1),q=[a.q[0]*(1-u)+b.q[0]*u,a.q[1]*(1-u)+b.q[1]*u];pts.push([path[j][0]*(1-e)+q[0]*e,path[j][1]*(1-e)+q[1]*e]);}}return pts;};
   const nodes=cell.vertices.map((v,i)=>({v,q:dest[i]}));
   if(geometry.k===1){const front=[];for(let i=0;i<3;i++){const a=nodes[i],b=nodes[(i+1)%3],ina=a.v[2]>=0,inb=b.v[2]>=0;if(ina)front.push(a);if(ina!==inb){const u=a.v[2]/(a.v[2]-b.v[2]);front.push({v:M.norm(a.v.map((x,j)=>x*(1-u)+b.v[j]*u),1),q:a.q.map((x,j)=>x*(1-u)+b.q[j]*u)});}}if(front.length>=3){ctx.globalAlpha=fade*(1-t);polygon(sampled(front),fill,'#193c43',.65);}ctx.globalAlpha=fade*t;polygon(sampled(nodes),fill,'#193c43',.65);
   }else{ctx.globalAlpha=fade;polygon(sampled(nodes),fill,'#193c43',.65);}
  }ctx.globalAlpha=1;if(clipDisc)ctx.restore();
 }
 if(t>.7){
  ctx.globalAlpha=Math.min(1,(t-.7)/.3);const highlighted=net.seams[seamIndex];
  if($('show-pairs').checked){const skip=Math.max(1,Math.floor(net.seams.length/32));for(let i=0;i<net.seams.length;i+=skip)pairArc(net.seams[i],false);}
  if(highlighted){pairArc(highlighted,true);for(const b of [highlighted.first,highlighted.second]){segment(net.positions[b.start],net.positions[b.end],'#ffdda5',5);const p=screen(midpoint(b));ctx.fillStyle='#ffdda5';ctx.beginPath();ctx.arc(...p,5,0,Math.PI*2);ctx.fill();ctx.font='12px -apple-system,sans-serif';ctx.textAlign='center';ctx.fillText('e'+highlighted.edge,p[0],p[1]-12);}}
  polygon(trianglePoints(selected),'#e5b77f99','#ffe4a9',2);ctx.globalAlpha=1;
 }
 if(wordPath.length){
  if(t>.6){for(let i=1;i<wordPath.length;i++){const a=wordPath[i-1],b=wordPath[i],side=data.neighbors[a].indexOf(b),cut=side>=0&&!net.treeEdges.has(data.faceEdges[a][side]);segment(centroid(a),centroid(b),'#ffdb85',2.2,cut);}}
  if(t<.4&&wordMatrices.length){for(let i=1;i<wordMatrices.length;i++){const a=M.mv(wordMatrices[i-1],geometry.center),b=M.mv(wordMatrices[i],geometry.center);if(geometry.k===1&&a[2]<0&&b[2]<0)continue;pathLine(curve(a,b,10),'#ffdb85',2.6);}}
 }
 ctx.restore();
 $('scene').setAttribute('aria-label',t<.5?`${geometry.name} triangle tessellation for (${data.signature.join(',')}). ${patch.length} displayed chambers. Two colors distinguish orientation; gold marks the selected quotient chamber.`:`Exact triangulation of ${data.surface}, genus ${data.genus}, drawn as a cut-open polygon with paired sides. ${fmt(data.counts.triangles)} triangles, ${fmt(data.counts.edges)} edges, ${fmt(data.counts.vertices)} vertices after gluing.`);
}
function midpoint(b){const p=net.positions[b.start],q=net.positions[b.end];return [(p[0]+q[0])/2,(p[1]+q[1])/2];}
function pairArc(pair,active){const a=screen(midpoint(pair.first)),b=screen(midpoint(pair.second)),c=screen([0,0]);ctx.beginPath();ctx.moveTo(...a);ctx.quadraticCurveTo(c[0],c[1],...b);ctx.strokeStyle=active?'#ffdc95':seamColor(pair.edge)+'45';ctx.lineWidth=active?2.3:.8;ctx.setLineDash(active?[5,4]:[]);ctx.stroke();ctx.setLineDash([]);}
function resize(){const r=canvas.getBoundingClientRect();width=r.width;height=r.height;const d=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(width*d);canvas.height=Math.round(height*d);draw();detail();}
function setProgress(t){progress=M.clamp(t,0,1);$('progress').value=progress;$('progress-text').textContent=progress<.03?'Tiling':progress>.97?'Surface':Math.round(progress*100)+'%';$('view-caption').textContent=progress<.4?`${geometry.name} cover · ${fmt(patch.length)} chambers shown`:`${fmt(data.counts.triangles)} triangles · ${fmt(net.seams.length)} cut pairs`;$('diagram-note').textContent=progress<.4?'Teal and dark triangles distinguish chamber orientation. Gold marks the selected quotient chamber or word. The cover keeps its original geometry.':'This is the triangulated surface cut into a disk. Glue each paired boundary side. The disk is a topological drawing; the original triangle metrics give the Riemann surface.';draw();}
function stop(){cancelAnimationFrame(anim);anim=0;$('animate').textContent='Animate quotient';}
function animate(){if(anim){stop();return;}progress=0;const start=performance.now(),duration=matchMedia('(prefers-reduced-motion:reduce)').matches?1500:9000;$('animate').textContent='Pause';function tick(now){setProgress(Math.min(1,(now-start)/duration));if(progress<1)anim=requestAnimationFrame(tick);else stop();}anim=requestAnimationFrame(tick);}
function detail(){if(!data)return;const c=$('chamber-detail'),r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);c.width=r.width*d;c.height=r.height*d;const cc=c.getContext('2d');cc.setTransform(d,0,0,d,0,0);const v=[[r.width/2,24],[26,r.height-28],[r.width-26,r.height-28]];cc.beginPath();v.forEach((p,i)=>i?cc.lineTo(...p):cc.moveTo(...p));cc.closePath();cc.fillStyle=selected%2?'#d9e4e2':'#e5ecd7';cc.fill();cc.strokeStyle='#4c8174';cc.lineWidth=1.5;cc.stroke();cc.textAlign='center';cc.font='13px -apple-system,sans-serif';for(let i=0;i<3;i++){cc.fillStyle=colors[i];cc.beginPath();cc.arc(...v[i],6,0,2*Math.PI);cc.fill();cc.fillStyle='#183b36';cc.fillText(`${['p','q','r'][i]}=${data.signature[i]}`,v[i][0],v[i][1]+(i?19:-13));const a=v[(i+1)%3],b=v[(i+2)%3];cc.fillText(`${'abc'[i]} → ${data.neighbors[selected][i]}`,(a[0]+b[0])/2,(a[1]+b[1])/2-7);}cc.font='18px Georgia';cc.fillText((selected%2?'−':'＋')+Math.floor(selected/2),r.width/2,r.height*.62);}
function selectFace(f){selected=M.clamp(Math.floor(Number(f)||0),0,data.counts.triangles-1);$('face-number').value=selected;$('face-info').textContent=`${selected%2?'Negative':'Positive'} chamber of group element ${Math.floor(selected/2)}. Vertices ${data.faceVertices[selected].join(', ')}.`;for(let i=0;i<3;i++)$('side-'+i).textContent=`Cross ${'abc'[i]} · ${data.neighbors[selected][i]}`;detail();draw();}
function selectSeam(i){seamIndex=M.clamp(Math.floor(Number(i)||0),0,net.seams.length-1);$('seam-number').value=seamIndex+1;const s=net.seams[seamIndex];$('seam-info').textContent=`Edge e${s.edge}: chamber ${s.first.face}, side ${'abc'[s.first.side]}, pairs with chamber ${s.second.face}, side ${'abc'[s.second.side]}. Endpoints match by vertex type.`;draw();}
function setSlide(n,move=true){slide=M.clamp(n,0,5);$('chapter-number').textContent=String(slide+1).padStart(2,'0');$('slide-position').textContent=`${slide+1} / 6`;$('previous').disabled=slide===0;$('next').disabled=slide===5;document.querySelectorAll('[data-slide]').forEach(b=>{const active=Number(b.dataset.slide)===slide;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'step':'false');});const [p,q,r]=data.signature,N=fmt(data.order),group=esc(groupName(data.group)),surface=esc(data.surface),v=data.counts;
 const chapters=[
 ['The triangle tessellation',`<p>Three mirror angles are π/${p}, π/${q}, π/${r}. Reflections generate <strong>T</strong>. Pairs of reflections generate its orientation-preserving subgroup <strong>T′</strong>.</p><p>One triangular chamber is a domain for T. <strong>Two chambers</strong> form a domain for T′.</p><p>Predict the geometry from 1/${p} + 1/${q} + 1/${r}. Then compare neighboring chambers.</p>`,`x = bc, y = ca, z = ab<br>x<sup>${p}</sup> = y<sup>${q}</sup> = z<sup>${r}</sup> = xyz = 1`],
 ['The chosen finite quotient',`<p>Send x and y to the following permutations. They generate <strong>${group}</strong>, of order ${N}.</p><p>The images have exact orders ${p}, ${q}, ${r}. Consequently the triangle-group relations hold and give a surjection φ.</p><p class="small">x = ${esc(cycles(data.cycles.x))}<br>y = ${esc(cycles(data.cycles.y))}<br>z = (xy)⁻¹</p>`,`φ: T′(${p},${q},${r}) → ${group}<br>K = ker φ`],
 ['Identifying kernel translates',`<p>Two even words have the same image in G precisely when their quotient lies in <strong>K</strong>.</p><p>The animation moves the visible cover triangles to their images in a finite chamber complex. Repeated lifts collapse to the same chamber.</p><p>The surface is <strong>X = ${geometry.k===1?'S²':geometry.k===0?'ℝ²':'ℍ²'} / K</strong>. The finite group G then acts on X.</p>`,`[T′ : K] = ${N}<br>${N} paired domains = ${fmt(v.triangles)} triangles`],
 [surface,`<p>This closed Riemann surface has <strong>genus ${data.genus}</strong>. Its triangles retain angles π/${p}, π/${q}, π/${r}.</p><p>The display cuts the surface along edges to make one disk. Every cut side has a partner. Select a pair below and glue endpoints of the same type.</p><p>${data.id==='m11'?'M₁₁ is the smallest sporadic Mathieu group. This particular action has signature (2,4,11); no standard surface name is assigned here.':data.id==='klein'?'The Klein quartic is the smooth plane curve x³y + y³z + z³x = 0.':data.id==='a6'?'The Wiman sextic is a smooth plane curve of degree 6 with automorphism group A₆.':data.id==='macbeath'?'The Fricke–Macbeath curve is a Hurwitz surface of genus 7.':data.id==='torus'?'The kernel is a lattice of translations. Its quotient is a torus with hexagonal conformal structure.':'The quotient is the Riemann sphere with its polyhedral rotation action.'}</p>`,`${2*p}, ${2*q}, ${2*r} triangles around vertices<br>Total angle at every vertex = 2π`],
 ['Counting the genus',`<p>Start with <strong>F = 2|G|</strong> triangles. Every edge belongs to two triangles, so E = 3|G|.</p><p>There are |G|/${p}, |G|/${q}, |G|/${r} vertices of the three types. Count them and use χ = V − E + F = 2 − 2g.</p><p>For this example: ${fmt(v.vertices)} − ${fmt(v.edges)} + ${fmt(v.triangles)} = <strong>${v.euler}</strong>.</p>`,`g = 1 + |G|/2 (1 − 1/p − 1/q − 1/r)<br>g = ${data.genus}`],
 ['Words become closed loops',`<p>The word explorer below multiplies the actual permutations. A word with image 1 gives a closed gallery in this quotient.</p><p>A nontrivial kernel word can return on X while ending in a different chamber of the cover. Compare the two ends using the identification slider.</p><p>Triangle relators already close in the universal tessellation. An <strong>extra relation</strong> can close only after taking the quotient.</p>`,`w ∈ K ⇔ φ(w) = 1<br>π₁(X) ≅ K`]
 ];
 $('chapter-title').innerHTML=chapters[slide][0];$('narrative').innerHTML=chapters[slide][1];$('equation').innerHTML=chapters[slide][2];$('facts').innerHTML=`<p>${group} · order ${N} · signature (${p},${q},${r})</p><p>${surface} · genus ${data.genus}</p><p>V = ${fmt(v.vertices)}, E = ${fmt(v.edges)}, F = ${fmt(v.triangles)}</p>`;
 if(move){stop();if(slide<2)setProgress(0);else if(slide===2)animate();else setProgress(1);} }
function traceWord(){stop();try{const parsed=M.parseWord($('word').value,'T′');wordPath=[0];for(const s of parsed.letters)wordPath.push(data.neighbors[wordPath.at(-1)]['abc'.indexOf(s)]);wordMatrices=M.wordMatrices(geometry,parsed.letters);const result=wordPath.at(-1),matrix=wordMatrices.at(-1),err=Math.max(...matrix.map((x,i)=>Math.abs(x-M.I()[i]))),inKernel=result===0;let description=inKernel?'Image in '+groupName(data.group)+': identity. The quotient gallery closes.':'Image in '+groupName(data.group)+': element '+Math.floor(result/2)+'. The quotient gallery stays open.';description+=inKernel?(err<1e-6?' It also closes in the cover.':' Its lift ends in a different cover chamber: an extra kernel relation.'):(err<1e-6?'':'');$('word-result').textContent=description;selectFace(result);setSlide(5,false);draw();}catch(e){$('word-result').textContent=e.message;wordPath=[];wordMatrices=[];draw();}}
function sampleWords(){const [p,q,r]=data.signature;const extra=data.extraRelator?.word;const words=['x^'+p,'y^'+q,'z^'+r,'xyz',extra||'xyXY','xy'];$('word-samples').replaceChildren(...[...new Set(words)].map(w=>{const b=document.createElement('button');b.textContent=w;b.onclick=()=>{$('word').value=w;traceWord();};return b;}));$('word').value=extra||'xyz';}
async function choose(id){const token=++loadToken;stop();$('geometry-label').textContent='Preparing triangulation…';await new Promise(resolve=>requestAnimationFrame(resolve));if(token!==loadToken)return;data=all[id];geometry=M.makeGeometry(...data.signature);net=QuotientNet.build(data);patch=sourcePatch();wordPath=[];wordMatrices=[];zoom=1;pan=[0,0];$('example').value=id;$('face-number').max=data.counts.triangles-1;$('seam-number').max=net.seams.length;$('geometry-label').textContent=`${geometry.name} · (${data.signature.join(', ')})`;$('chamber-label').textContent=`${groupName(data.group)} · genus ${data.genus}`;selectFace(0);selectSeam(0);sampleWords();setSlide(slide,false);setProgress(slide<2?0:1);document.querySelectorAll('[data-example]').forEach(row=>row.classList.toggle('selected',row.dataset.example===id));$('sources').innerHTML=(data.sources||[]).map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a></li>`).join('');$('proof-text').innerHTML=`<p>Let Δ = T′(${data.signature.join(',')}) and let φ: Δ → ${esc(groupName(data.group))} be the displayed surjection. Its three elliptic generators have exactly the indicated orders. Every torsion element in an oriented triangle group is conjugate to a power of an elliptic vertex stabilizer, so K = ker φ has no nontrivial torsion. It acts freely, and X = ${geometry.k===1?'S²':geometry.k===0?'ℝ²':'ℍ²'}/K is a smooth closed oriented surface.</p><p>Label the chambers (g,+) and (g,−). Cross c from (g,+) to (g,−), b to (gx,−), and a to (gy⁻¹,−). Reverse those rules from negative chambers. No assumption that K is normal in the full reflection group is needed. The finite group is Δ/K; the surface is the geometric cover divided by K.</p><p>To draw X, retain a spanning tree of the dual chamber graph and cut every other edge. The result is a triangulated disk with ${fmt(data.counts.triangles+2)} sides. Its ${fmt(net.seams.length)} pairs of boundary sides reconstruct exactly the original complex. Dashed word-path segments cross these cuts. Pairing arcs are guides, not additional edges of the triangulation.</p><p>Every displayed triangle is a cell of this complex. In small quotients distinct edges can have the same endpoint pair, so we keep their edge IDs. This is a triangular cell decomposition (a Δ-complex). The genus follows from its exact cell counts. The animation illustrates identification of chambers and is not an isometric deformation of the cover into an embedded surface in three-dimensional space.</p>`;resize();history.replaceState(null,'','#'+id);}
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(all?.[id]&&data?.id!==id)choose(id);});
$('example').onchange=()=>choose($('example').value);document.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>setSlide(+b.dataset.slide));$('previous').onclick=()=>setSlide(slide-1);$('next').onclick=()=>setSlide(slide+1);$('animate').onclick=animate;$('progress').oninput=()=>{stop();setProgress(+$('progress').value);};$('face-number').onchange=()=>selectFace($('face-number').value);for(let side=0;side<3;side++)$('side-'+side).onclick=()=>selectFace(data.neighbors[selected][side]);$('seam-number').onchange=()=>selectSeam(+$('seam-number').value-1);$('show-seam').onclick=()=>{setSlide(3);selectSeam(+$('seam-number').value-1);};$('show-pairs').onchange=draw;$('word-form').onsubmit=e=>{e.preventDefault();traceWord();};$('zoom-in').onclick=()=>{zoom=Math.min(30,zoom*1.3);draw();};$('zoom-out').onclick=()=>{zoom=Math.max(.6,zoom/1.3);draw();};$('reset-view').onclick=()=>{zoom=1;pan=[0,0];draw();};
canvas.onwheel=e=>{e.preventDefault();const rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left-width/2,y=e.clientY-rect.top-height/2,f=e.deltaY<0?1.12:1/1.12,newZoom=M.clamp(zoom*f,.6,30),ratio=newZoom/zoom;pan=[x-(x-pan[0])*ratio,y-(y-pan[1])*ratio];zoom=newZoom;draw();};canvas.onpointerdown=e=>{if(e.button!==0)return;canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,id:e.pointerId};};canvas.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;pan[0]+=e.clientX-drag.x;pan[1]+=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;draw();};canvas.onpointerup=e=>{if(!drag)return;const click=Math.hypot(e.clientX-drag.sx,e.clientY-drag.sy)<5;drag=null;if(click&&progress>.7){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let best=Infinity,index=0;net.seams.forEach((s,i)=>{for(const b of [s.first,s.second]){const p=screen(midpoint(b)),d=Math.hypot(x-p[0],y-p[1]);if(d<best){best=d;index=i;}}});if(best<30)selectSeam(index);}};canvas.onpointercancel=()=>drag=null;canvas.onkeydown=e=>{if(e.key==='ArrowRight'){e.preventDefault();selectFace(data.neighbors[selected][0]);}if(e.key==='Home'){$('reset-view').click();}};document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='PageDown'){e.preventDefault();setSlide(slide+1);}if(e.key==='PageUp'){e.preventDefault();setSlide(slide-1);}});new ResizeObserver(resize).observe(canvas);
(async()=>{try{const bytes=Uint8Array.from(atob(window.QUOTIENT_PACKED),c=>c.charCodeAt(0));all=JSON.parse(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text());window.QUOTIENT_PACKED=undefined;$('comparison-body').innerHTML=Object.values(all).map(d=>`<tr data-example="${d.id}" tabindex="0"><td>${esc(groupName(d.group))}</td><td>(${d.signature.join(',')})</td><td>${fmt(d.order)}</td><td>${d.genus}</td><td>${esc(d.surface)}</td></tr>`).join('');document.querySelectorAll('[data-example]').forEach(row=>{row.onclick=()=>choose(row.dataset.example);row.onkeydown=e=>{if(e.key==='Enter')choose(row.dataset.example);};});await choose(all[location.hash.slice(1)]?location.hash.slice(1):'klein');}catch(e){$('error').hidden=false;$('error').textContent='Could not prepare the quotient: '+e.message;console.error(e);}})();
})();
