import {curves,geometry,add,sub,mul,dot,cross,norm,unit,planeEquation,circlePoint} from './math.mjs';
const $=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d');
let curve=curves[0],t=0,playing=false,view='world',lastFrame=0,uiTime=0,width=800,height=550,dpr=1;
let cameraDistance=curve.distance,worldOrbit={yaw:-.88,pitch:.47},rideOrbit={yaw:.2,pitch:.48};
let arrowScale=.65,showLabels=true,geometryNow=geometry(curve,t),camera=null,path=[],renderQueue=[],labels=[];
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const layerSpecs=[
 ['r','Position · r','#8faef7',false,'vector'],['v','Velocity · v = r′','#62ded1',false,'vector'],['a','Acceleration · a = r″','#ffb06d',false,'vector'],
 ['T','Unit tangent · T','#6dcff4',true,'vector'],['N','Principal normal · N','#b2e58a',true,'vector'],['B','Binormal · B','#c6a7f3',true,'vector'],
 ['aT','Tangential acceleration · aₜT','#fb9978',false,'vector'],['aN','Normal acceleration · aₙN','#f2d467',false,'vector'],
 ['curvature','Curvature κ & radius ρ','#f4e1ad',true,'geometry'],['normalPlane','Normal plane','#bea5ed',false,'geometry'],['osculatingPlane','Osculating plane','#5fc5bf',false,'geometry'],['circle','Osculating circle','#f1bd6d',true,'geometry']
];
const layers=Object.fromEntries(layerSpecs.map(([id,,,checked])=>[id,checked]));
for(const [id,title,color,checked,group] of layerSpecs){const row=document.createElement('label');row.className='check-row';row.innerHTML=`<input type="checkbox" id="layer-${id}" ${checked?'checked':''}><span>${title}</span><i class="swatch" style="--swatch:${color}" aria-hidden="true"></i>`;$(group+'-toggles').append(row);row.querySelector('input').addEventListener('change',e=>{layers[id]=e.target.checked;updateUI();draw()})}
for(const c of curves){const option=document.createElement('option');option.value=c.id;option.textContent=c.name;$('curve').append(option)}
const observations={helix:'On the Lecture 6 helix, speed and curvature are constant. Acceleration points entirely in the normal direction.',wavy:'The wavy ring leaves its plane. Watch B rotate as the osculating plane changes from point to point.',trefoil:'A knot can loop around itself in space. The local moving frame follows the curve through every twist.',ellipse:'Changing speed adds tangential acceleration. The normal component still measures how sharply the velocity turns.',parabola:'At the bottom of the swoop, the bend is sharpest and the osculating circle is smallest.',spiral:'As the corkscrew expands, the local circle changes size. Both the direction and magnitude of velocity change.',line:'A straight line has κ = 0 and a = 0. T and the normal plane exist, but the principal normal and osculating circle do not.'};
function fmt(n,p=3){if(n===null||!Number.isFinite(n))return 'undefined';if(Math.abs(n)<.5*10**(-p))n=0;return n.toFixed(p)}
const vec=a=>a?'⟨'+a.map(n=>fmt(n)).join(', ')+'⟩':'undefined (κ = 0)';
function planeText(n,p){if(!n)return 'Undefined because κ = 0.';const eq=planeEquation(n,p);return `${fmt(n[0])}x ${n[1]<0?'−':'+'} ${fmt(Math.abs(n[1]))}y ${n[2]<0?'−':'+'} ${fmt(Math.abs(n[2]))}z = ${fmt(eq.constant)}`}
function updateUI(){
 const g=geometryNow;
 if($('fs-time')){$('fs-time').value=Math.round(1000*(t-curve.range[0])/(curve.range[1]-curve.range[0]));$('fs-time-output').textContent='t = '+fmt(t);$('fs-curve').value=curve.id;for(const [id]of layerSpecs){$('fs-layer-'+id).checked=layers[id];$('fs-layer-'+id).disabled=['N','B','osculatingPlane','circle'].includes(id)&&!g.N}}
 $('time-output').textContent=`t = ${fmt(t)}`;$('time').value=Math.round(1000*(t-curve.range[0])/(curve.range[1]-curve.range[0]));
 $('curvature-value').textContent=fmt(g.kappa);$('speed-value').textContent=fmt(g.speed);$('radius-value').textContent=g.rho?fmt(g.rho):'∞';
 $('curvature-value').parentElement.hidden=!layers.curvature;$('radius-value').parentElement.hidden=!layers.curvature;
 $('singular-note').hidden=!!g.N;if(view==='ride'){$('view-label').textContent=g.N?'MOVING FRENET FRAME':'STRAIGHT-LINE RIDE FRAME';$('coordinate-label').textContent=g.N?'camera turns with T, N, B':'straight line: fixed transverse frame'}
 const values=[['Position r(t)',vec(g.r)],['Velocity v = r′(t)',vec(g.v)],['Acceleration a = r″(t)',vec(g.a)],['Unit tangent T = v / |v|',vec(g.T)],['Principal normal N = B × T',vec(g.N)],['Binormal B = (v × a) / |v × a|',vec(g.B)],['Tangential scalar aₜ = (v · a) / |v|',fmt(g.aT)],['Normal scalar aₙ = |v × a| / |v|',fmt(g.aN)],['Tangential vector aₜT',vec(mul(g.T,g.aT))],['Normal vector aₙN',g.N?vec(mul(g.N,g.aN)):'⟨0.000, 0.000, 0.000⟩'],['Curvature κ = |v × a| / |v|³',fmt(g.kappa)],['Radius of curvature ρ = 1/κ',g.rho?fmt(g.rho):'∞ (no finite circle)']];
 $('live-values').innerHTML=values.map(([label,value])=>`<div class="value-row"><span>${label}</span><span>${value}</span></div>`).join('');
 $('normal-equation').textContent=planeText(g.T,g.r);$('osculating-equation').textContent=planeText(g.B,g.r);
 $('circle-equation').textContent=g.center?`C = ${vec(g.center)}; ρ = ${fmt(g.rho)}. c(θ) = ${vec(g.center)} − ${vec(mul(g.N,g.rho))} cos θ + ${vec(mul(g.T,g.rho))} sin θ, 0 ≤ θ ≤ 2π.`:'No finite osculating circle: κ = 0. The normal part of acceleration is the zero vector.';
 for(const id of ['N','B','osculatingPlane','circle']){$('layer-'+id).disabled=!g.N}
}
function setPlaying(next){playing=next;if($('fs-play')){$('fs-play').textContent=playing?'Ⅱ Pause':'▶ Play'};$('play').innerHTML=playing?'Ⅱ <span>Pause</span>':'▶ <span>Play</span>';$('play').setAttribute('aria-label',playing?'Pause animation':'Start animation');$('motion-status').textContent=playing?'ON THE MOVE':'PAUSED';document.querySelector('.live-pill').classList.toggle('running',playing)}
function buildPath(){path=[];const n=curve.id==='helix'||curve.id==='spiral'?1000:700;for(let i=0;i<=n;i++){const u=curve.range[0]+(curve.range[1]-curve.range[0])*i/n;const g=geometry(curve,u);path.push(g)}}
function setCurve(){curve=curves.find(c=>c.id===$('curve').value);t=curve.range[0];cameraDistance=curve.distance;geometryNow=geometry(curve,t);$('track-formula').textContent=curve.formula;$('track-description').textContent=curve.subtitle;$('v-formula').textContent=curve.velocity;$('a-formula').textContent=curve.acceleration;$('extra-formula').textContent=curve.extra||'';$('extra-formula').hidden=!curve.extra;$('observation').textContent=observations[curve.id];buildPath();updateUI();draw()}
function setView(next){view=next;for(const id of ['world','ride']){$(id+'-view').classList.toggle('selected',id===view);$(id+'-view').setAttribute('aria-pressed',String(id===view))}$('view-label').textContent=view==='world'?'WORLD FRAME':'MOVING FRENET FRAME';$('camera-help').textContent=view==='world'?'Axes keep their orientation while the camera follows the point.':'Your seat follows T, N and B as the track turns. On a straight line, a fixed transverse frame is used. Drag to look around.';$('coordinate-label').textContent=view==='world'?'x, y, z = world orientation':'camera turns with T, N, B';updateUI();draw()}
function cameraFrame(){
 const g=geometryNow,o=view==='world'?worldOrbit:rideOrbit;let back,upRef;
 if(view==='world'){back=[Math.cos(o.yaw)*Math.cos(o.pitch),Math.sin(o.yaw)*Math.cos(o.pitch),Math.sin(o.pitch)];upRef=[0,0,1]}
 else{const T=g.T||[1,0,0],B=g.B||[0,0,1],N=g.N||cross(B,T);back=add(add(mul(T,-Math.cos(o.yaw)*Math.cos(o.pitch)),mul(N,Math.sin(o.yaw)*Math.cos(o.pitch))),mul(B,Math.sin(o.pitch)));upRef=B}
 const forward=mul(back,-1),right=unit(cross(forward,upRef))||[1,0,0],up=unit(cross(right,forward));
 return {target:g.r,back,right,up,distance:cameraDistance*(view==='ride'?.77:1),focal:Math.min(width,height)*1.15,cx:width*.52,cy:height*.57};
}
function project(p){const q=sub(p,camera.target),depth=camera.distance-dot(q,camera.back);if(depth<.25)return null;return {x:camera.cx+dot(q,camera.right)*camera.focal/depth,y:camera.cy-dot(q,camera.up)*camera.focal/depth,depth,scale:camera.focal/depth}}
function strokeLine(a,b,color,lineWidth=1,dash=[]){const p=project(a),q=project(b);if(!p||!q)return;if(Math.abs(p.x)>width*20||Math.abs(p.y)>height*20||Math.abs(q.x)>width*20||Math.abs(q.y)>height*20)return;renderQueue.push({depth:(p.depth+q.depth)/2,draw:()=>{ctx.strokeStyle=color;ctx.lineWidth=lineWidth;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.setLineDash([])}})}
function polygon(points,fill,stroke){const ps=points.map(project);if(ps.some(p=>!p))return;renderQueue.push({depth:ps.reduce((s,p)=>s+p.depth,0)/ps.length,draw:()=>{ctx.beginPath();ps.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}}})}
function queueLabel(text,p,color,priority=0){const q=project(p);if(q&&q.x>12&&q.x<width-12&&q.y>135&&q.y<height-80)labels.push({text,x:q.x,y:q.y,color,priority})}
function arrow(origin,value,color,label){if(!value)return;if(norm(value)<1e-8){if(label)queueLabel(label+' = 0',add(origin,[0,0,-.24]),color);return}const end=add(origin,mul(value,arrowScale));strokeLine(origin,end,color,2.4);const p=project(origin),q=project(end);if(!p||!q)return;renderQueue.push({depth:q.depth-.02,draw:()=>{const angle=Math.atan2(q.y-p.y,q.x-p.x),size=8;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(q.x,q.y);ctx.lineTo(q.x-size*Math.cos(angle-.42),q.y-size*Math.sin(angle-.42));ctx.lineTo(q.x-size*Math.cos(angle+.42),q.y-size*Math.sin(angle+.42));ctx.closePath();ctx.fill()}});if(label)queueLabel(label,end,color,2)}
function planePatch(origin,u,v,color){const s=1.45;polygon([add(origin,add(mul(u,s),mul(v,s))),add(origin,add(mul(u,-s),mul(v,s))),add(origin,add(mul(u,-s),mul(v,-s))),add(origin,add(mul(u,s),mul(v,-s)))],color+'19',color+'6a');for(let i=-1;i<=1;i++){strokeLine(add(origin,add(mul(u,i*.72),mul(v,-s))),add(origin,add(mul(u,i*.72),mul(v,s))),color+'24');strokeLine(add(origin,add(mul(v,i*.72),mul(u,-s))),add(origin,add(mul(v,i*.72),mul(u,s))),color+'24')}}
function drawTrack(){
 for(let i=1;i<path.length;i++){const g=path[i],last=path[i-1];const near=Math.abs((curve.range[0]+(curve.range[1]-curve.range[0])*i/(path.length-1))-t)<.5;const alpha=near?'c7':'67';const side=g.N||[0,1,0],prevSide=last.N||[0,1,0];strokeLine(add(last.r,mul(prevSide,-.095)),add(g.r,mul(side,-.095)),'#6c9cac'+alpha,1.4);strokeLine(add(last.r,mul(prevSide,.095)),add(g.r,mul(side,.095)),'#79afba'+alpha,1.4);if(i%13===0)strokeLine(add(g.r,mul(side,-.15)),add(g.r,mul(side,.15)),'#6989977a',2)}
}
function drawGrid(){
 const g=geometryNow,base=[Math.round(g.r[0]/2)*2,Math.round(g.r[1]/2)*2,Math.floor(g.r[2]/2)*2-2];for(let i=-5;i<=5;i++){strokeLine(add(base,[-10,i*2,0]),add(base,[10,i*2,0]),'#789ba214',1);strokeLine(add(base,[i*2,-10,0]),add(base,[i*2,10,0]),'#789ba214',1)}
 if(layers.r){strokeLine([0,0,0],g.r,'#8faef7a8',1.8,[5,4]);const dir=unit(g.r);if(dir){const len=Math.min(norm(g.r),.7);arrow(sub(g.r,mul(dir,len)),mul(dir,len/arrowScale),'#8faef7','r')}queueLabel('O',[0,0,0],'#8faef7')}
}
function drawGeometry(){const g=geometryNow,N=g.N||[0,1,0],B=g.B||[0,0,1];
 if(layers.normalPlane){planePatch(g.r,N,B,'#bea5ed');queueLabel('normal plane',add(g.r,add(mul(N,1.45),mul(B,1.45))),'#cdb7f0')}
 if(layers.osculatingPlane&&g.N){planePatch(g.r,g.T,g.N,'#5fc5bf');queueLabel('osculating plane',add(g.r,add(mul(g.T,-1.45),mul(g.N,-1.45))),'#72d4ce')}
 if(layers.circle&&g.center&&g.rho<1000){let previous=circlePoint(g,0);for(let i=1;i<=180;i++){const p=circlePoint(g,2*Math.PI*i/180);strokeLine(previous,p,'#f1bd6db0',1.5,[3,3]);previous=p}queueLabel('osculating circle',circlePoint(g,Math.PI*.85),'#f1bd6d')}
 if(layers.curvature&&g.center&&g.rho<1000){strokeLine(g.r,g.center,'#f4e1ad7a',1.2,[4,4]);const center=project(g.center);if(center)renderQueue.push({depth:center.depth,draw:()=>{ctx.strokeStyle='#f4e1ad';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(center.x-4,center.y);ctx.lineTo(center.x+4,center.y);ctx.moveTo(center.x,center.y-4);ctx.lineTo(center.x,center.y+4);ctx.stroke()}});queueLabel('C',g.center,'#f4e1ad');queueLabel('ρ = '+fmt(g.rho,2),add(g.r,mul(g.N,g.rho*.6)),'#f4e1ad')}
 const defs=[['v',g.v,'v'],['a',g.a,'a'],['T',g.T,'T'],['N',g.N,'N'],['B',g.B,'B'],['aT',mul(g.T,g.aT),'aₜT'],['aN',g.N?mul(g.N,g.aN):[0,0,0],'aₙN']];for(const [id,value,label]of defs)if(layers[id])arrow(g.r,value,layerSpecs.find(s=>s[0]===id)[2],label);
}
function cart(){const g=geometryNow,T=g.T,N=g.N||[0,1,0],B=g.B||[0,0,1],at=(x,y,z)=>add(g.r,add(mul(T,x),add(mul(N,y),mul(B,z))));
 const top=[at(.24,.19,.13),at(-.24,.19,.13),at(-.24,-.19,.13),at(.24,-.19,.13)];
 polygon([at(.24,.19,0),at(-.24,.19,0),top[1],top[0]],'#e87549','#ffb977');polygon([at(-.24,-.19,0),at(.24,-.19,0),top[3],top[2]],'#a65139','#db8b5f');polygon([at(.24,.19,0),at(.24,-.19,0),top[3],top[0]],'#ce6240','#ffb977');polygon(top,'#ffab6f','#ffd1a5');
 for(const x of [-.17,.17])for(const y of [-.21,.21]){const p=project(at(x,y,-.025));if(p)renderQueue.push({depth:p.depth-.001,draw:()=>{ctx.fillStyle='#1b2b37';ctx.strokeStyle='#d2ded5';ctx.lineWidth=1.3;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(2,Math.min(6,p.scale*.047)),0,Math.PI*2);ctx.fill();ctx.stroke()}})}

}
function drawLabels(){if(!showLabels)return;const occupied=[];ctx.font='13px -apple-system, sans-serif';ctx.textBaseline='middle';ctx.textAlign='left';labels.sort((a,b)=>b.priority-a.priority);for(const label of labels){const textWidth=ctx.measureText(label.text).width+12;let x=label.x+10,y=label.y-12;for(let attempt=0;attempt<10;attempt++){const box={x,y:y-10,w:textWidth,h:21};if(x+textWidth>width-10)x=label.x-textWidth-10;if(!occupied.some(b=>box.x<b.x+b.w&&box.x+box.w>b.x&&box.y<b.y+b.h&&box.y+box.h>b.y)){occupied.push(box);break}y+=21}if(y>height-55||y<135)continue;ctx.fillStyle='#102437dd';ctx.beginPath();ctx.roundRect(x-3,y-9,textWidth,18,4);ctx.fill();ctx.fillStyle=label.color;ctx.fillText(label.text,x+2,y)}}
function compass(){const cx=width-55,cy=height-91;ctx.font='10px Georgia,serif';ctx.textAlign='center';ctx.textBaseline='middle';for(const [v,label,color]of [[[1,0,0],'x','#ed937f'],[[0,1,0],'y','#93c78e'],[[0,0,1],'z','#85b8e0']]){const dx=dot(v,camera.right)*25,dy=-dot(v,camera.up)*25;ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+dx,cy+dy);ctx.stroke();ctx.fillStyle=color;ctx.fillText(label,cx+dx*1.35,cy+dy*1.35)}}
function draw(){if(!width||!height)return;camera=cameraFrame();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);const gradient=ctx.createRadialGradient(width*.5,height*.5,0,width*.5,height*.5,width*.72);gradient.addColorStop(0,'#16344a');gradient.addColorStop(1,'#0c1f30');ctx.fillStyle=gradient;ctx.fillRect(0,0,width,height);renderQueue=[];labels=[];drawGrid();drawTrack();drawGeometry();cart();renderQueue.sort((a,b)=>b.depth-a.depth);for(const primitive of renderQueue)primitive.draw();drawLabels();compass()}
function resize(){const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);draw()}
new ResizeObserver(resize).observe(canvas);
$('curve').addEventListener('change',setCurve);$('world-view').addEventListener('click',()=>setView('world'));$('ride-view').addEventListener('click',()=>setView('ride'));
$('play').addEventListener('click',()=>{if(!playing&&t>=curve.range[1])t=curve.range[0];setPlaying(!playing)});$('restart').addEventListener('click',()=>{t=curve.range[0];geometryNow=geometry(curve,t);updateUI();draw()});
$('time').addEventListener('input',e=>{t=curve.range[0]+Number(e.target.value)/1000*(curve.range[1]-curve.range[0]);geometryNow=geometry(curve,t);updateUI();draw()});
$('reset-camera').addEventListener('click',()=>{worldOrbit={yaw:-.88,pitch:.47};rideOrbit={yaw:.2,pitch:.48};cameraDistance=curve.distance;draw()});
function zoom(factor){cameraDistance=Math.min(35,Math.max(2.2,cameraDistance*factor));draw()}
$('zoom-in').addEventListener('click',()=>zoom(.85));$('zoom-out').addEventListener('click',()=>zoom(1/.85));
$('vector-scale').addEventListener('input',e=>{arrowScale=Number(e.target.value);$('scale-output').textContent=arrowScale.toFixed(2)+'×';draw()});$('labels').addEventListener('change',e=>{showLabels=e.target.checked;draw()});
for(const [button,checked]of [['show-all',true],['hide-all',false]])$(button).addEventListener('click',()=>{for(const[id]of layerSpecs){layers[id]=checked;$('layer-'+id).checked=checked}updateUI();draw()});
let pointer=null;
canvas.addEventListener('pointerdown',e=>{pointer={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const orbit=view==='world'?worldOrbit:rideOrbit;orbit.yaw-=(e.clientX-pointer.x)*.007;orbit.pitch=Math.max(-1.35,Math.min(1.35,orbit.pitch+(e.clientY-pointer.y)*.007));pointer.x=e.clientX;pointer.y=e.clientY;draw()});
canvas.addEventListener('pointerup',()=>pointer=null);canvas.addEventListener('pointercancel',()=>pointer=null);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(e.deltaY*.001))},{passive:false});
canvas.addEventListener('keydown',e=>{const o=view==='world'?worldOrbit:rideOrbit;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')o.yaw+=.1;else if(e.key==='ArrowRight')o.yaw-=.1;else if(e.key==='ArrowUp')o.pitch=Math.min(1.35,o.pitch+.1);else if(e.key==='ArrowDown')o.pitch=Math.max(-1.35,o.pitch-.1);else if(e.key==='+'||e.key==='=')zoom(.9);else if(e.key==='-')zoom(1/.9);else if(e.key===' ')setPlaying(!playing);draw()});
document.addEventListener('visibilitychange',()=>{lastFrame=0});
function tick(now){const delta=lastFrame?Math.min((now-lastFrame)/1000,.06):0;lastFrame=now;if(playing&&!document.hidden){let ended=false;t+=delta*Number($('playback-speed').value);if(t>curve.range[1]){if(curve.closed)t=curve.range[0]+(t-curve.range[1]);else{t=curve.range[1];setPlaying(false);ended=true}}geometryNow=geometry(curve,t);draw();if(ended||now-uiTime>80){updateUI();uiTime=now}}requestAnimationFrame(tick)}
const fullscreen=document.createElement('button');fullscreen.type='button';fullscreen.className='fullscreen-button';fullscreen.textContent='⛶ Full screen';fullscreen.setAttribute('aria-label','Expand animation to full screen');$('stage').append(fullscreen);fullscreen.addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else {await $('stage').requestFullscreen();canvas.focus()}}catch{ $('stage').classList.toggle('expanded-stage');fullscreen.textContent=$('stage').classList.contains('expanded-stage')?'× Close full screen':'⛶ Full screen';canvas.focus()}});document.addEventListener('fullscreenchange',()=>{fullscreen.textContent=document.fullscreenElement?'× Exit full screen':'⛶ Full screen';resize()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('stage').classList.contains('expanded-stage')){$('stage').classList.remove('expanded-stage');fullscreen.textContent='⛶ Full screen'}});
const fullscreenDock=document.createElement('div');fullscreenDock.className='fullscreen-dock';
fullscreenDock.innerHTML=`<button id="fs-play">▶ Play</button><button id="fs-restart" aria-label="Restart track">↺</button><div class="fullscreen-time"><label for="fs-time" id="fs-time-output">t = 0.000</label><input id="fs-time" type="range" min="0" max="1000" step="1" value="0"></div><button id="fs-view">Switch seat</button><button id="fs-layers" aria-expanded="false" aria-controls="fs-panel">Track & layers</button>`;
$('stage').append(fullscreenDock);
const fullscreenPanel=document.createElement('div');fullscreenPanel.className='fullscreen-panel';fullscreenPanel.id='fs-panel';fullscreenPanel.hidden=true;
fullscreenPanel.innerHTML='<label for="fs-curve">Choose your track</label><select id="fs-curve">'+$('curve').innerHTML+'</select><label for="fs-speed">Time rate</label><select id="fs-speed">'+$('playback-speed').innerHTML+'</select><p>Make motion visible</p>';
for(const [id,title,color,checked]of layerSpecs){const row=document.createElement('label');row.className='check-row';row.innerHTML=`<input type="checkbox" id="fs-layer-${id}" ${checked?'checked':''}><span>${title}</span><i class="swatch" style="--swatch:${color}" aria-hidden="true"></i>`;fullscreenPanel.append(row);row.querySelector('input').addEventListener('change',e=>{layers[id]=e.target.checked;$('layer-'+id).checked=e.target.checked;updateUI();draw()})}
$('stage').append(fullscreenPanel);
$('fs-play').addEventListener('click',()=>$('play').click());$('fs-restart').addEventListener('click',()=>$('restart').click());$('fs-view').addEventListener('click',()=>setView(view==='world'?'ride':'world'));
$('fs-layers').addEventListener('click',()=>{fullscreenPanel.hidden=!fullscreenPanel.hidden;$('fs-layers').setAttribute('aria-expanded',String(!fullscreenPanel.hidden))});
$('fs-curve').addEventListener('change',e=>{$('curve').value=e.target.value;setCurve()});$('fs-speed').value=$('playback-speed').value;
$('fs-speed').addEventListener('change',e=>$('playback-speed').value=e.target.value);$('playback-speed').addEventListener('change',e=>$('fs-speed').value=e.target.value);
$('fs-time').addEventListener('input',e=>{t=curve.range[0]+Number(e.target.value)/1000*(curve.range[1]-curve.range[0]);geometryNow=geometry(curve,t);updateUI();draw()});
setCurve();setPlaying(!reducedMotion);requestAnimationFrame(tick);
