import {surfaces,byId,defaults,makeSlice,slicePoint,exactSlice} from './math.mjs';
const $=id=>document.getElementById(id),canvas=$('scene'),stage=$('stage');
const gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true});
const state={id:'ellipsoid',p:{...defaults},bound:2.4,n:42,axis:2,h:0,azimuth:-.8,elevation:.48,zoom:1.2,spin:false,slice:true,cutaway:false,axes:true,nodes:false,palette:'jade'};
const palettes={jade:[[.20,.46,.36],[.71,.76,.55]],clay:[[.69,.33,.22],[.86,.65,.42]],iris:[[.40,.35,.61],[.76,.64,.76]],blue:[[.25,.44,.59],[.62,.76,.75]]};
let mesh=null,worker=null,meshTimer=null,meshVersion=0,sectionSegments=new Float32Array(),sectionPoints=[],frameRequested=false,lastTime=0;
let surfaceProgram,lineProgram,pointProgram,positionBuffer,normalBuffer,lineBuffer,pointBuffer,matrix;
const VERTEX=`attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uMatrix;varying vec3 vPosition;varying vec3 vNormal;void main(){vPosition=aPosition;vNormal=aNormal;gl_Position=uMatrix*vec4(aPosition,1.0);}`;
const FRAGMENT=`precision highp float;varying vec3 vPosition;varying vec3 vNormal;uniform vec3 uColor;uniform vec3 uBack;uniform vec3 uEye;uniform float uBound;uniform bool uCut;uniform int uAxis;uniform float uHeight;void main(){float coordinate=uAxis==0?vPosition.x:(uAxis==1?vPosition.y:vPosition.z);if(uCut&&coordinate>uHeight+0.00001)discard;vec3 n=normalize(vNormal);if(!gl_FrontFacing)n=-n;vec3 view=normalize(uEye-vPosition);float key=max(dot(n,normalize(vec3(-0.5,-0.8,1.5))),0.0);float fill=max(dot(n,normalize(vec3(1.0,0.7,0.2))),0.0);float rim=pow(1.0-max(dot(n,view),0.0),2.8);vec3 base=gl_FrontFacing?uColor:uBack;float shift=0.04*vPosition.z/uBound;vec3 color=base*(0.48+0.66*key+0.21*fill)+vec3(0.18,0.18,0.13)*rim+shift;vec3 halfdir=normalize(normalize(vec3(-0.5,-0.8,1.5))+view);color+=vec3(0.30,0.29,0.23)*pow(max(dot(n,halfdir),0.0),48.0);gl_FragColor=vec4(color,1.0);}`;
const LINE_VERTEX=`attribute vec3 aPosition;uniform mat4 uMatrix;uniform float uPointSize;void main(){gl_Position=uMatrix*vec4(aPosition,1.0);gl_PointSize=uPointSize;}`;
const LINE_FRAGMENT=`precision mediump float;uniform vec4 uColor;void main(){gl_FragColor=uColor;}`;
const POINT_FRAGMENT=`precision mediump float;uniform vec4 uColor;void main(){float d=length(gl_PointCoord-vec2(0.5));if(d>0.5)discard;gl_FragColor=vec4(mix(uColor.rgb,vec3(1.0,0.95,0.77),smoothstep(0.33,0.47,d)),uColor.a);}`;
function createProgram(vertex,fragment){const shaders=[gl.VERTEX_SHADER,gl.FRAGMENT_SHADER].map((type,i)=>{const s=gl.createShader(type);gl.shaderSource(s,i===0?vertex:fragment);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;});const p=gl.createProgram();shaders.forEach(s=>gl.attachShader(p,s));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));shaders.forEach(s=>gl.deleteShader(s));return p;}
function initializeGL(){if(!gl){showError('This view needs WebGL. Enable hardware acceleration or try a current browser. The equations and slice view remain available.');return;}try{surfaceProgram=createProgram(VERTEX,FRAGMENT);lineProgram=createProgram(LINE_VERTEX,LINE_FRAGMENT);pointProgram=createProgram(LINE_VERTEX,POINT_FRAGMENT);positionBuffer=gl.createBuffer();normalBuffer=gl.createBuffer();lineBuffer=gl.createBuffer();pointBuffer=gl.createBuffer();gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(.937,.945,.914,1);}catch(error){showError('The 3D renderer could not start: '+error.message);}}
function showError(message){$('canvas-error').hidden=false;$('canvas-error').textContent=message;}
const normalize=a=>{const n=Math.hypot(...a);return a.map(v=>v/n);};
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
function multiply(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function cameraMatrix(){const b=state.bound,aspect=canvas.width/canvas.height,d=b*4.4/state.zoom*Math.max(1,1.12/aspect),eye=[d*Math.cos(state.elevation)*Math.cos(state.azimuth),d*Math.cos(state.elevation)*Math.sin(state.azimuth),d*Math.sin(state.elevation)],z=normalize(eye),x=normalize(cross([0,0,1],z)),y=cross(z,x);const view=new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);const f=1/Math.tan(Math.PI*38/360),near=.02,far=150,projection=new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);return {matrix:multiply(projection,view),eye};}
function attribute(program,name,buffer,size=3){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);const location=gl.getAttribLocation(program,name);if(location<0)return;gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,size,gl.FLOAT,false,0,0);}
function uniform(program,name,type,...value){const location=gl.getUniformLocation(program,name);if(type==='matrix')gl.uniformMatrix4fv(location,false,value[0]);else gl['uniform'+type](location,...value);}
function drawLines(points,color,mode=gl.LINES,depth=true){if(!points.length)return;gl.useProgram(lineProgram);gl.bindBuffer(gl.ARRAY_BUFFER,lineBuffer);gl.bufferData(gl.ARRAY_BUFFER,points instanceof Float32Array?points:new Float32Array(points),gl.DYNAMIC_DRAW);attribute(lineProgram,'aPosition',lineBuffer);uniform(lineProgram,'uMatrix','matrix',matrix);uniform(lineProgram,'uColor','4fv',color);if(!depth)gl.disable(gl.DEPTH_TEST);gl.drawArrays(mode,0,points.length/3);gl.enable(gl.DEPTH_TEST);}
function drawPoints(points,color,size=9){if(!points.length)return;gl.useProgram(pointProgram);gl.bindBuffer(gl.ARRAY_BUFFER,pointBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(points.flat()),gl.DYNAMIC_DRAW);attribute(pointProgram,'aPosition',pointBuffer);uniform(pointProgram,'uMatrix','matrix',matrix);uniform(pointProgram,'uColor','4fv',color);uniform(pointProgram,'uPointSize','1f',size*Math.min(devicePixelRatio,2));gl.disable(gl.DEPTH_TEST);gl.drawArrays(gl.POINTS,0,points.length);gl.enable(gl.DEPTH_TEST);}

function draw(){frameRequested=false;if(!gl||!surfaceProgram)return;const {matrix:m,eye}=cameraMatrix();matrix=m;gl.viewport(0,0,canvas.width,canvas.height);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);
 if(state.axes){const b=state.bound,box=[];for(let axis=0;axis<3;axis++)for(let u of [-b,b])for(let v of [-b,b]){const a=[0,0,0],c=[0,0,0],others=[0,1,2].filter(j=>j!==axis);a[axis]=-b;c[axis]=b;a[others[0]]=c[others[0]]=u;a[others[1]]=c[others[1]]=v;box.push(...a,...c);}drawLines(box,[.59,.64,.54,.3]);}
 if(mesh){gl.useProgram(surfaceProgram);attribute(surfaceProgram,'aPosition',positionBuffer);attribute(surfaceProgram,'aNormal',normalBuffer);uniform(surfaceProgram,'uMatrix','matrix',matrix);uniform(surfaceProgram,'uColor','3fv',palettes[state.palette][0]);uniform(surfaceProgram,'uBack','3fv',palettes[state.palette][1]);uniform(surfaceProgram,'uEye','3fv',eye);uniform(surfaceProgram,'uBound','1f',state.bound);uniform(surfaceProgram,'uCut','1i',state.slice&&state.cutaway?1:0);uniform(surfaceProgram,'uAxis','1i',state.axis);uniform(surfaceProgram,'uHeight','1f',state.h);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,1);gl.drawArrays(gl.TRIANGLES,0,mesh.positions.length/3);gl.disable(gl.POLYGON_OFFSET_FILL);}
 if(state.axes){const b=state.bound;[[.66,.38,.29,.6],[.34,.50,.37,.6],[.34,.44,.63,.6]].forEach((color,i)=>{const a=[0,0,0],c=[0,0,0];a[i]=-b;c[i]=b;drawLines([...a,...c],color);});}
 if(state.slice){const b=state.bound,h=state.h,a=state.axis,p=[slicePoint(a,h,-b,-b),slicePoint(a,h,b,-b),slicePoint(a,h,b,b),slicePoint(a,h,-b,b)];gl.depthMask(false);drawLines([...p[0],...p[1],...p[2],...p[0],...p[2],...p[3]],[.75,.53,.22,.08],gl.TRIANGLES);drawLines([...p[0],...p[1],...p[1],...p[2],...p[2],...p[3],...p[3],...p[0]],[.66,.45,.15,.45]);const segments=[];for(let i=0;i<sectionSegments.length;i+=2)segments.push(...slicePoint(a,h,sectionSegments[i],sectionSegments[i+1]));drawLines(segments,[.73,.46,.13,1],gl.LINES,false);gl.depthMask(true);}
 if(state.slice&&sectionPoints.length)drawPoints(sectionPoints.map(p=>slicePoint(state.axis,state.h,...p)),[.73,.46,.13,1]);
 if(state.nodes){const nodes=(byId[state.id].nodes?.(state.p)||[]).filter(p=>p.every(v=>Math.abs(v)<=state.bound)&&!(state.slice&&state.cutaway&&p[state.axis]>state.h+1e-9));drawPoints(nodes,[.7,.32,.12,1]);}
 updateAxisLabels();
}
function requestDraw(){if(!frameRequested){frameRequested=true;requestAnimationFrame(draw);}}
function updateAxisLabels(){const labels=document.querySelectorAll('.axis-label');labels.forEach((element,i)=>{const p=[0,0,0,1];p[i]=state.bound;const out=[0,1,2,3].map(r=>p.reduce((s,v,k)=>s+matrix[k*4+r]*v,0));const x=(out[0]/out[3]*.5+.5)*canvas.clientWidth,y=(-out[1]/out[3]*.5+.5)*canvas.clientHeight;element.hidden=!state.axes||out[3]<0||x<0||y<0||x>canvas.clientWidth||y>canvas.clientHeight;element.style.left=(x+3)+'px';element.style.top=(y-9)+'px';});}
function updateMesh(delay=0){clearTimeout(meshTimer);worker?.terminate();const version=++meshVersion;$('mesh-status').textContent='Building surface…';meshTimer=setTimeout(()=>{worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(version!==meshVersion)return;if(data.error){showError(data.error);$('mesh-status').textContent='Mesh unavailable';return;}mesh=data;if(gl&&surfaceProgram){gl.bindBuffer(gl.ARRAY_BUFFER,positionBuffer);gl.bufferData(gl.ARRAY_BUFFER,mesh.positions,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,normalBuffer);gl.bufferData(gl.ARRAY_BUFFER,mesh.normals,gl.STATIC_DRAW);}$('mesh-status').textContent=mesh.triangles.toLocaleString()+' triangles · ±'+state.bound.toFixed(2);worker.terminate();worker=null;requestDraw();};worker.onerror=event=>{showError('Mesh generation failed: '+event.message);$('mesh-status').textContent='Mesh unavailable';};worker.postMessage({id:state.id,p:state.p,bound:state.bound,n:state.n});},delay);}
function updateCoefficients(){const names=byId[state.id].params;$('coefficient-line').textContent=names.map(name=>`${name} = ${state.p[name].toFixed(2)}`).join('     ·     ');}
function selectSurface(id){state.id=id;const surface=byId[id];state.p={...defaults};state.bound=surface.bound;state.h=surface.initialSlice||0;state.zoom=id==='ellipsoid'||id==='sphere'?1.2:1;state.nodes=false;$('nodes').checked=false;$('surface').value=id;$('surface-title').textContent=surface.name;$('surface-note').textContent=surface.note;$('equation').textContent=surface.equation;$('extra-equation').textContent=surface.extra||'';$('extra-equation').hidden=!surface.extra;$('observation').textContent=surface.prompt;$('degree-badge').textContent='DEGREE '+surface.degree;const gallery=surface.group==='Algebraic gallery';$('quadrics-tab').classList.toggle('selected',!gallery);$('quadrics-tab').setAttribute('aria-pressed',String(!gallery));$('gallery-tab').classList.toggle('selected',gallery);$('gallery-tab').setAttribute('aria-pressed',String(gallery));$('parameters').replaceChildren();for(const name of surface.params){const wrap=document.createElement('div'),label=document.createElement('label'),output=document.createElement('output'),range=document.createElement('input');label.className='range-label';label.htmlFor='parameter-'+name;label.append(document.createTextNode(name==='t'?'Level t':name==='a'&&id==='sphere'?'Radius a':'Semiaxis / scale '+name));output.value=state.p[name].toFixed(2);label.append(output);range.id='parameter-'+name;range.type='range';range.min=name==='t'?-1:.4;range.max=name==='t'?1:2;range.step=.05;range.value=state.p[name];range.addEventListener('input',()=>{state.p[name]=Number(range.value);output.value=state.p[name].toFixed(2);updateCoefficients();updateNodeControl();updateSlice();updateMesh(110);});wrap.append(label,range);$('parameters').append(wrap);}updateCoefficients();updateNodeControl();$('view-bound').value=state.bound;updateBound(false);updateMesh();}
function updateNodeControl(){const nodes=byId[state.id].nodes?.(state.p)||[];$('node-control').hidden=!nodes.length;$('node-control').querySelector('span').textContent=`Mark ${nodes.length} verified affine ${nodes.length===1?'node':'nodes'}`;}
function updateBound(rebuild=true){$('bound-output').value=state.bound.toFixed(2);$('slice-height').min=-state.bound;$('slice-height').max=state.bound;state.h=Math.min(state.bound,Math.max(-state.bound,state.h));$('slice-height').value=state.h;updateSlice();if(rebuild)updateMesh(150);}
function updateSlice(){const axis='xyz'[state.axis],surface=byId[state.id];$('height-output').value=state.h.toFixed(2);$('plane-label').textContent=state.slice?`${axis} = ${state.h.toFixed(2)}`:'Slice hidden';$('section-label').textContent=`${axis} = ${state.h.toFixed(2)}`;$('section-title').textContent=state.axis===2?'The horizontal trace':'A vertical trace';$('slice-math').textContent=state.axis===2?surface.section:`Set ${axis} = ${state.h.toFixed(2)} in F(x,y,z) = 0. The panel plots the resulting equation in the other two coordinates.`;const exact=exactSlice(surface,state.p,state.axis,state.h,state.bound);sectionPoints=exact?.points||[];if(exact)$('slice-math').textContent+=' '+exact.note;sectionSegments=makeSlice(surface,state.p,state.axis,state.h,state.bound,160);drawSlice();requestDraw();}
function drawSlice(){const c=$('section'),rect=c.parentElement.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,Math.round(rect.width*dpr));c.height=Math.max(1,Math.round(rect.height*dpr));const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const W=rect.width,H=rect.height,pad=24,scale=Math.max(1,Math.min(W,H)-2*pad)/(2*state.bound),cx=W/2,cy=H/2;ctx.clearRect(0,0,W,H);ctx.strokeStyle='#dde2d4';ctx.lineWidth=1;const step=state.bound>2?1:.5;for(let v=-Math.floor(state.bound/step)*step;v<=state.bound;v+=step){ctx.beginPath();ctx.moveTo(cx+v*scale,cy-state.bound*scale);ctx.lineTo(cx+v*scale,cy+state.bound*scale);ctx.moveTo(cx-state.bound*scale,cy-v*scale);ctx.lineTo(cx+state.bound*scale,cy-v*scale);ctx.stroke();}ctx.strokeStyle='#a2ae99';ctx.beginPath();ctx.moveTo(cx-state.bound*scale,cy);ctx.lineTo(cx+state.bound*scale,cy);ctx.moveTo(cx,cy-state.bound*scale);ctx.lineTo(cx,cy+state.bound*scale);ctx.stroke();ctx.strokeStyle='#b57d2c';ctx.lineWidth=1.8;ctx.beginPath();for(let i=0;i<sectionSegments.length;i+=4){ctx.moveTo(cx+sectionSegments[i]*scale,cy-sectionSegments[i+1]*scale);ctx.lineTo(cx+sectionSegments[i+2]*scale,cy-sectionSegments[i+3]*scale);}ctx.stroke();ctx.fillStyle='#b57d2c';for(const p of sectionPoints){ctx.beginPath();ctx.arc(cx+p[0]*scale,cy-p[1]*scale,3.5,0,2*Math.PI);ctx.fill();}ctx.fillStyle='#798771';ctx.font='italic 12px Georgia';const names=['x','y','z'].filter((_,i)=>i!==state.axis);ctx.fillText(names[0],cx+state.bound*scale+5,cy-4);ctx.fillText(names[1],cx+5,cy-state.bound*scale-5);ctx.font='9px system-ui';ctx.fillText('0',cx+4,cy+12);if(!sectionSegments.length&&!sectionPoints.length){ctx.textAlign='center';ctx.fillStyle='#8c7d5f';ctx.fillText('No sampled contour',cx,16);ctx.textAlign='start';}}
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(canvas.clientWidth*dpr));canvas.height=Math.max(1,Math.round(canvas.clientHeight*dpr));drawSlice();requestDraw();}
function resetCamera(){state.azimuth=-.8;state.elevation=.48;state.zoom=state.id==='ellipsoid'||state.id==='sphere'?1.2:1;requestDraw();}
function toggleSpin(){state.spin=!state.spin;$('spin').setAttribute('aria-pressed',String(state.spin));$('spin').textContent=state.spin?'Ⅱ Stop turning':'↻ Turntable';lastTime=0;if(state.spin)requestAnimationFrame(animate);}
function animate(t){if(!state.spin)return;if(lastTime)state.azimuth+=(t-lastTime)*.00018;lastTime=t;requestDraw();requestAnimationFrame(animate);}
for(const group of ['Quadrics','Algebraic gallery']){const optgroup=document.createElement('optgroup');optgroup.label=group;for(const surface of surfaces.filter(s=>s.group===group)){const option=document.createElement('option');option.value=surface.id;option.textContent=surface.name;optgroup.append(option);}$('surface').append(optgroup);}
$('surface').addEventListener('change',e=>selectSurface(e.target.value));$('quadrics-tab').addEventListener('click',()=>selectSurface('ellipsoid'));$('gallery-tab').addEventListener('click',()=>selectSurface('barth'));
$('slice-axis').addEventListener('change',e=>{state.axis=Number(e.target.value);updateSlice();});$('slice-height').addEventListener('input',e=>{state.h=Number(e.target.value);updateSlice();});$('zero-slice').addEventListener('click',()=>{state.h=0;$('slice-height').value=0;updateSlice();});$('slice-enabled').addEventListener('change',e=>{state.slice=e.target.checked;$('cutaway').disabled=!state.slice;updateSlice();});$('cutaway').addEventListener('change',e=>{state.cutaway=e.target.checked;requestDraw();});$('axes').addEventListener('change',e=>{state.axes=e.target.checked;requestDraw();});$('nodes').addEventListener('change',e=>{state.nodes=e.target.checked;requestDraw();});$('quality').addEventListener('change',e=>{state.n=Number(e.target.value);updateMesh();});$('palette').addEventListener('change',e=>{state.palette=e.target.value;requestDraw();});$('view-bound').addEventListener('input',e=>{state.bound=Number(e.target.value);updateBound();});$('reset').addEventListener('click',resetCamera);$('spin').addEventListener('click',toggleSpin);$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.requestFullscreen();}catch{$('mesh-status').textContent='Fullscreen unavailable in this browser';}});
const pointers=new Map();let oldPinch=0;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);canvas.focus({preventScroll:true});if(pointers.size===2){const q=[...pointers.values()];oldPinch=Math.hypot(q[1][0]-q[0][0],q[1][1]-q[0][1]);}});
canvas.addEventListener('pointermove',e=>{const prev=pointers.get(e.pointerId);if(!prev)return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===1){state.azimuth-=(e.clientX-prev[0])*.008;state.elevation=Math.max(-1.45,Math.min(1.45,state.elevation+(e.clientY-prev[1])*.008));}else if(pointers.size===2){const q=[...pointers.values()],distance=Math.hypot(q[1][0]-q[0][0],q[1][1]-q[0][1]);if(oldPinch>0)state.zoom=Math.max(.45,Math.min(3,state.zoom*distance/oldPinch));oldPinch=distance;}requestDraw();});
for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,e=>pointers.delete(e.pointerId));
canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.45,Math.min(3,state.zoom*Math.exp(-e.deltaY*.001)));requestDraw();},{passive:false});
canvas.addEventListener('keydown',e=>{let handled=true;switch(e.key){case'ArrowLeft':state.azimuth+=.1;break;case'ArrowRight':state.azimuth-=.1;break;case'ArrowUp':state.elevation=Math.min(1.45,state.elevation+.1);break;case'ArrowDown':state.elevation=Math.max(-1.45,state.elevation-.1);break;case'+':case'=':state.zoom=Math.min(3,state.zoom*1.1);break;case'-':state.zoom=Math.max(.45,state.zoom/1.1);break;case'Home':resetCamera();break;case' ':toggleSpin();break;default:handled=false;}if(handled){e.preventDefault();requestDraw();}});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();showError('The graphics context was interrupted. Reload this page to restore the surface.');});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.spin)toggleSpin();});
initializeGL();new ResizeObserver(resize).observe(stage);new ResizeObserver(drawSlice).observe($('section').parentElement);const requested=new URLSearchParams(location.search).get('surface');selectSurface(Object.hasOwn(byId,requested)?requested:'ellipsoid');resize();
// Read-only snapshot for reproducible local browser checks.
window.surfaceExplorer={getState:()=>({...state,p:{...state.p},triangles:mesh?.triangles||0}),getSurfaceIds:()=>surfaces.map(s=>s.id)};
