/* Polynomial level sets. No expression parser or dynamic evaluation. */
export const PHI=(1+Math.sqrt(5))/2;
export const defaults={a:1.5,b:1,c:1.25,t:0};
const scaled=(x,y,z,p)=>[x/p.a,y/p.b,z/p.c];
export const T6=x=>32*x**6-48*x**4+18*x*x-1;
export const dT6=x=>192*x**5-192*x**3+36*x;
const signs=[-1,1];
const cyclic=v=>[v,[v[1],v[2],v[0]],[v[2],v[0],v[1]]];
export function kummerNodes(){const points=[];for(const z of [-1/Math.sqrt(2),1/Math.sqrt(2)])for(const a of signs)for(const b of signs)points.push([a*(1-z)/Math.sqrt(2),b*(1+z)/Math.sqrt(2),z]);for(const s of signs)points.push([0,s,1],[s,0,-1],[0,s/Math.sqrt(2),.5],[s/Math.sqrt(2),0,-.5]);return points;}
export function barthNodes(){const points=[];for(const a of signs)for(const b of signs)for(const c of signs){points.push([a,b,c]);points.push(...cyclic([a*PHI/2,b*(PHI-1)/2,c/2]));}for(const a of signs)for(const b of signs)points.push(...cyclic([0,a*(PHI-1),b*PHI]));for(const a of signs)points.push(...cyclic([a,0,0]));return points;}
export function chebyshevNodes(){const points=[];for(const a of [-.5,.5])for(const b of [-.5,.5])for(const c of [-Math.sqrt(3)/2,0,Math.sqrt(3)/2])points.push(...cyclic([a,b,c]));return points;}
const quad=(sign,constant)=>(x,y,z,p)=>{const [u,v,w]=scaled(x,y,z,p);return u*u+sign[0]*v*v+sign[1]*w*w-constant;};
const quadGrad=sign=>(x,y,z,p)=>[2*x/p.a**2,2*sign[0]*y/p.b**2,2*sign[1]*z/p.c**2];
export const surfaces=[
 {id:'ellipsoid',group:'Quadrics',name:'Ellipsoid',degree:2,equation:'x²/a² + y²/b² + z²/c² = 1',field:quad([1,1],1),grad:quadGrad([1,1]),bound:2.4,params:['a','b','c'],note:'A closed surface with three semiaxes. Equal semiaxes give a sphere.',prompt:'Move the horizontal slice. Why do its ellipses shrink to a point at the top and bottom?',section:'At z = h: x²/a² + y²/b² = 1 − h²/c². Ellipse for |h| < c, one point for |h| = c, empty for |h| > c.'},
 {id:'sphere',group:'Quadrics',name:'Sphere',degree:2,equation:'x² + y² + z² = a²',field:(x,y,z,p)=>x*x+y*y+z*z-p.a*p.a,grad:(x,y,z)=>[2*x,2*y,2*z],bound:2.4,params:['a'],note:'Every point lies the same distance a from the origin.',prompt:'For which heights h is the horizontal section a circle? What is its radius?',section:'At z = h: x² + y² = a² − h². Radius √(a² − h²) for |h| ≤ a.'},
 {id:'one-sheet',group:'Quadrics',name:'One-sheet hyperboloid',degree:2,equation:'x²/a² + y²/b² − z²/c² = 1',field:quad([1,-1],1),grad:quadGrad([1,-1]),bound:2.4,params:['a','b','c'],note:'One connected surface, with an elliptical waist. It is also a doubly ruled surface.',prompt:'Compare horizontal ellipses with a vertical hyperbola. Can you imagine the straight lines lying on the surface?',section:'At z = h: x²/a² + y²/b² = 1 + h²/c². Every horizontal section is an ellipse.'},
 {id:'translated-hyperboloid',group:'Quadrics',name:'A translated hyperboloid',degree:2,equation:'(x − 1)²/4 + (y + 1)² − (z − 2)²/4 = 1',field:(x,y,z)=>(x-1)**2/4+(y+1)**2-(z-2)**2/4-1,grad:(x,y,z)=>[(x-1)/2,2*(y+1),-(z-2)/2],bound:4,initialSlice:2,params:[],note:'The one-sheet hyperboloid is centered at (1,−1,2), with scales a = 2, b = 1, c = 2. Translation moves its waist to z = 2.',prompt:'Find the center before classifying the surface. How do the shifts x − 1, y + 1, and z − 2 move its horizontal traces?',section:'At z = h: (x − 1)²/4 + (y + 1)² = 1 + (h − 2)²/4. The smallest ellipse occurs at h = 2, centered at (1,−1).'},
 {id:'two-sheet',group:'Quadrics',name:'Two-sheet hyperboloid',degree:2,equation:'z²/c² − x²/a² − y²/b² = 1',field:(x,y,z,p)=>z*z/p.c**2-x*x/p.a**2-y*y/p.b**2-1,grad:(x,y,z,p)=>[-2*x/p.a**2,-2*y/p.b**2,2*z/p.c**2],bound:2.8,params:['a','b','c'],note:'Two disconnected sheets, separated by the empty region −c < z < c.',prompt:'Sweep the slice through the gap. At what heights do the first points appear?',section:'At z = h: x²/a² + y²/b² = h²/c² − 1. Empty for |h| < c; points at ±c; ellipses outside.'},
 {id:'cone',group:'Quadrics',name:'Elliptic cone',degree:2,equation:'x²/a² + y²/b² − z²/c² = 0',field:quad([1,-1],0),grad:quadGrad([1,-1]),bound:2.4,params:['a','b','c'],nodes:()=>[[0,0,0]],note:'Two nappes meet at the singular vertex. There is no unique tangent plane at the origin.',prompt:'The vertex belongs to the cone. What happens to ∇F there?',section:'At z = h: x²/a² + y²/b² = h²/c². Ellipses collapse to the vertex when h = 0.'},
 {id:'elliptic-paraboloid',group:'Quadrics',name:'Elliptic paraboloid',degree:2,equation:'z/c = x²/a² + y²/b²',field:(x,y,z,p)=>x*x/p.a**2+y*y/p.b**2-z/p.c,grad:(x,y,z,p)=>[2*x/p.a**2,2*y/p.b**2,-1/p.c],bound:2.4,params:['a','b','c'],note:'A bowl with one vertex. Its horizontal traces are ellipses, and vertical traces are parabolas.',prompt:'Unlike a cone, this vertex is a smooth point. Compare the two gradients.',section:'At z = h: x²/a² + y²/b² = h/c. Ellipses for h > 0, a point at h = 0, empty below.'},
 {id:'hyperbolic-paraboloid',group:'Quadrics',name:'Hyperbolic paraboloid',degree:2,equation:'z/c = x²/a² − y²/b²',field:(x,y,z,p)=>x*x/p.a**2-y*y/p.b**2-z/p.c,grad:(x,y,z,p)=>[2*x/p.a**2,-2*y/p.b**2,-1/p.c],bound:2.4,params:['a','b','c'],note:'A smooth saddle, ruled by two families of straight lines. Opposite curvatures meet at every point.',prompt:'At h = 0 the slice is two intersecting lines. Why does that not make the surface singular?',section:'At z = h: x²/a² − y²/b² = h/c. Hyperbolas for h ≠ 0, intersecting lines for h = 0.'},
 {id:'elliptic-cylinder',group:'Quadrics',name:'Elliptic cylinder',degree:2,equation:'x²/a² + y²/b² = 1',field:(x,y,z,p)=>x*x/p.a**2+y*y/p.b**2-1,grad:(x,y,z,p)=>[2*x/p.a**2,2*y/p.b**2,0],bound:2.4,params:['a','b'],note:'The equation is independent of z: translate the same ellipse along the vertical axis.',prompt:'Why does the horizontal trace remain unchanged as you move the plane?',section:'At z = h: the same ellipse x²/a² + y²/b² = 1, for every h.'},
 {id:'hyperbolic-cylinder',group:'Quadrics',name:'Hyperbolic cylinder',degree:2,equation:'x²/a² − y²/b² = 1',field:(x,y,z,p)=>x*x/p.a**2-y*y/p.b**2-1,grad:(x,y,z,p)=>[2*x/p.a**2,-2*y/p.b**2,0],bound:2.4,params:['a','b'],note:'A hyperbola extended in a direction absent from its equation.',prompt:'Switch between z and x slices. When do you obtain parallel lines?',section:'At z = h: the same hyperbola x²/a² − y²/b² = 1, for every h.'},
 {id:'parabolic-cylinder',group:'Quadrics',name:'Parabolic cylinder',degree:2,equation:'y/b = x²/a²',field:(x,y,z,p)=>x*x/p.a**2-y/p.b,grad:(x,y,z,p)=>[2*x/p.a**2,-1/p.b,0],bound:2.4,params:['a','b'],note:'A parabola extended parallel to the z-axis. A cylinder need not have circular sections.',prompt:'Which coordinate is missing from the equation? What does that tell you geometrically?',section:'At z = h: the same parabola y = b x²/a², for every h.'},
 {id:'transition',group:'Quadrics',name:'A quadric changes type',degree:2,equation:'x²/a² + y²/b² − z²/c² = t',field:(x,y,z,p)=>x*x/p.a**2+y*y/p.b**2-z*z/p.c**2-p.t,grad:quadGrad([1,-1]),bound:2.4,params:['a','b','c','t'],nodes:p=>p.t===0?[[0,0,0]]:[],note:'Vary t: a two-sheet hyperboloid (t < 0) passes through a cone (t = 0) to a one-sheet hyperboloid (t > 0).',prompt:'Watch the topology change at t = 0. The singular cone separates two smooth families.',section:'At z = h: x²/a² + y²/b² = t + h²/c². Its sign determines an ellipse, a point, or an empty section.'},
 {id:'planes',group:'Quadrics',name:'A pair of planes',degree:2,equation:'x² − y² = (x − y)(x + y) = 0',field:(x,y)=>x*x-y*y,grad:(x,y)=>[2*x,-2*y,0],bound:2.4,params:[],note:'A reducible quadric: the two planes x = y and x = −y. The entire z-axis is singular.',prompt:'Factor the equation. How does an algebraic factorization appear in the picture?',section:'At z = h: the same two lines y = ±x, intersecting at a point of the singular z-axis.'},
 {id:'cayley',group:'Algebraic gallery',name:'Cayley nodal cubic',degree:3,equation:'x² + y² + z² − 2xyz = 1',field:(x,y,z)=>x*x+y*y+z*z-2*x*y*z-1,grad:(x,y,z)=>[2*x-2*y*z,2*y-2*x*z,2*z-2*x*y],bound:1.75,params:[],nodes:()=>[[1,1,1],[1,-1,-1],[-1,1,-1],[-1,-1,1]],note:'A cubic with four ordinary double points, at (1,1,1), (1,−1,−1), (−1,1,−1), (−1,−1,1).',prompt:'Try a slice through z = 1. The cubic section becomes a double line.',section:'At z = 1: (x − y)² = 0, so the set-theoretic slice is the line x = y, counted twice algebraically.'},
 {id:'clebsch',group:'Algebraic gallery',name:'Clebsch diagonal cubic',degree:3,equation:'x³ + y³ + z³ + 1 − (x + y + z + 1)³ = 0',field:(x,y,z)=>x**3+y**3+z**3+1-(x+y+z+1)**3,grad:(x,y,z)=>{const q=3*(x+y+z+1)**2;return [3*x*x-q,3*y*y-q,3*z*z-q];},bound:2.1,params:[],note:'An affine chart of the smooth projective cubic ΣXᵢ = ΣXᵢ³ = 0 in ℙ⁴, with X₄ = 1 and X₅ = −x−y−z−1.',prompt:'This smooth projective cubic has 27 real lines. The displayed affine chart shows only the part inside the view box.',section:'Substitute the chosen plane coordinate into the cubic equation to obtain a plane cubic; some special sections are reducible.'},
 {id:'kummer',group:'Algebraic gallery',name:'Kummer quartic',degree:4,equation:'(x²+y²+z²−2)² − 5[(1−z)²−2x²][(1+z)²−2y²] = 0',field:(x,y,z)=>{const q=x*x+y*y+z*z-2,A=(1-z)**2-2*x*x,B=(1+z)**2-2*y*y;return q*q-5*A*B;},grad:(x,y,z)=>{const q=x*x+y*y+z*z-2,A=(1-z)**2-2*x*x,B=(1+z)**2-2*y*y;return [4*x*q+20*x*B,4*y*q+20*y*A,4*z*q+10*(1-z)*B-10*(1+z)*A];},bound:1.8,params:[],nodes:kummerNodes,note:'A member of the classical tetrahedral-coordinate family, with μ² = 2 and λ = 5. This Kummer quartic has exactly 16 real nodes, all finite in this chart.',prompt:'Compare the thin necks with actual singular points. Increasing resolution changes the mesh, not the polynomial.',section:'A generic plane section is a quartic curve. Special planes may meet nodes or split the section into components.'},
 {id:'chebyshev',group:'Algebraic gallery',name:'Chebyshev sextic',degree:6,equation:'T₆(x) + T₆(y) + T₆(z) = 1',extra:'T₆(u) = 32u⁶ − 48u⁴ + 18u² − 1',field:(x,y,z)=>T6(x)+T6(y)+T6(z)-1,grad:(x,y,z)=>[dT6(x),dT6(y),dT6(z)],bound:1.18,params:[],nodes:chebyshevNodes,note:'A separable Chebyshev construction with 36 real ordinary double points. Repeated folds reflect the oscillations of T₆.',prompt:'Its critical coordinates are cos(kπ/6), k = 1,…,5. Which triples also satisfy the surface equation?',section:'At z = h: T₆(x) + T₆(y) = 1 − T₆(h). A family of plane sextics.'},
 {id:'barth',group:'Algebraic gallery',name:'Barth sextic',degree:6,equation:'4(φ²x²−y²)(φ²y²−z²)(φ²z²−x²) − (1+2φ)(x²+y²+z²−1)² = 0',extra:'φ = (1 + √5)/2',field:(x,y,z)=>{const k=PHI**2,q=x*x+y*y+z*z-1;return 4*(k*x*x-y*y)*(k*y*y-z*z)*(k*z*z-x*x)-(1+2*PHI)*q*q;},grad:(x,y,z)=>{const k=PHI**2,A=k*x*x-y*y,B=k*y*y-z*z,C=k*z*z-x*x,q=x*x+y*y+z*z-1,d=1+2*PHI;return [8*x*(k*B*C-A*B)-4*d*x*q,8*y*(-B*C+k*A*C)-4*d*y*q,8*z*(-A*C+k*A*B)-4*d*z*q];},bound:1.95,params:[],nodes:barthNodes,note:'Wolf Barth’s icosahedrally symmetric sextic has 65 ordinary double points in projective space. This affine chart contains 50; 15 lie at infinity.',prompt:'Symmetry organizes the singularities, but a finite triangle mesh cannot certify or resolve every node.',section:'A generic plane section is a sextic. The 15 projective nodes at infinity cannot appear in this affine view.'}
];
export const byId=Object.fromEntries(surfaces.map(s=>[s.id,s]));
export function gradient(surface,x,y,z,p=defaults){return surface.grad(x,y,z,p);}
export function finiteGradient(field,x,y,z,p=defaults,h=1e-5){return [(field(x+h,y,z,p)-field(x-h,y,z,p))/(2*h),(field(x,y+h,z,p)-field(x,y-h,z,p))/(2*h),(field(x,y,z+h,p)-field(x,y,z-h,p))/(2*h)];}
export function slicePoint(axis,h,u,v){return axis===0?[h,u,v]:axis===1?[u,h,v]:[u,v,h];}
export function exactSlice(surface,p,axis,h,bound){
 const epsilon=1e-9,empty=()=>({segments:new Float32Array(),points:[],note:'This section is empty.'});
 const line=(u,v)=>new Float32Array([-u,-v,u,v]);
 if(surface.id==='cayley'&&Math.abs(Math.abs(h)-1)<epsilon)return {segments:line(bound,h*bound),points:[],note:`This section is one line, counted twice algebraically (a double line).`};
 if(surface.degree!==2)return null;
 // Recover the diagonal conic coefficients after substitution. All quadrics in
 // this library have no mixed terms, so this also classifies point/line traces.
 const f=(u,v)=>surface.field(...slicePoint(axis,h,u,v),p),c=f(0,0),d=(f(1,0)-f(-1,0))/2,e=(f(0,1)-f(0,-1))/2,a=(f(1,0)+f(-1,0))/2-c,b=(f(0,1)+f(0,-1))/2-c;
 if(Math.abs(d)>epsilon||Math.abs(e)>epsilon)return null;
 if(Math.abs(a)>epsilon&&Math.abs(b)>epsilon&&a*b>0){if(Math.abs(c)<epsilon)return {segments:new Float32Array(),points:[[0,0]],note:'This section is a single point, shown by the gold dot.'};if(c*a>0)return empty();}
 if(Math.abs(c)<epsilon){if(Math.abs(a)>epsilon&&Math.abs(b)<epsilon)return {segments:line(0,bound),points:[],note:'This section is a double line.'};if(Math.abs(b)>epsilon&&Math.abs(a)<epsilon)return {segments:line(bound,0),points:[],note:'This section is a double line.'};}
 if(Math.abs(a)<epsilon&&Math.abs(b)<epsilon){if(Math.abs(c)<epsilon)return {segments:new Float32Array(),points:[],note:'The entire coordinate plane lies on the surface.'};return empty();}
 return null;
}
// Two triangles per square avoid the ambiguous saddle case of marching squares.
export function makeSlice(surface,p,axis,h,bound,n=128){
 const exact=exactSlice(surface,p,axis,h,bound);if(exact)return exact.segments;
 const f=surface.field,step=2*bound/n,out=[],grid=new Float64Array((n+1)**2);
 for(let j=0;j<=n;j++)for(let i=0;i<=n;i++){const q=slicePoint(axis,h,-bound+i*step,-bound+j*step);grid[j*(n+1)+i]=f(...q,p);}
 for(let j=0;j<n;j++)for(let i=0;i<n;i++){
  const uv=[[i,j],[i+1,j],[i+1,j+1],[i,j+1]];
  for(const tri of [[0,1,2],[0,2,3]]){const hits=[];for(let e=0;e<3;e++){const aa=uv[tri[e]],bb=uv[tri[(e+1)%3]],fa=grid[aa[1]*(n+1)+aa[0]],fb=grid[bb[1]*(n+1)+bb[0]];if((fa>=0)===(fb>=0))continue;const t=fa/(fa-fb);hits.push([-bound+(aa[0]+t*(bb[0]-aa[0]))*step,-bound+(aa[1]+t*(bb[1]-aa[1]))*step]);}if(hits.length===2)out.push(...hits[0],...hits[1]);}
 }
 return new Float32Array(out);
}
