import assert from 'node:assert/strict';
import {surfaces,byId,defaults,finiteGradient,T6,makeSlice,exactSlice,slicePoint} from './math.mjs';
import {makeMesh} from './mesh.mjs';
const p={...defaults};let checks=0;
function near(actual,expected,tolerance,label){assert.ok(Math.abs(actual-expected)<=tolerance,`${label}: ${actual} vs ${expected}`);checks++;}
for(const surface of surfaces){for(let i=1;i<=40;i++){const q=[Math.sin(i*1.7),Math.cos(i*.9),Math.sin(i*.31)].map(v=>v*1.9);const analytic=surface.grad(...q,p),numeric=finiteGradient(surface.field,...q,p);analytic.forEach((v,j)=>near(v,numeric[j],1e-5*(1+Math.abs(v)),surface.id+' gradient'));}}
for(const [id,count] of [['cayley',4],['kummer',16],['chebyshev',36],['barth',50]]){const s=byId[id],nodes=s.nodes(p);assert.equal(nodes.length,count);assert.equal(new Set(nodes.map(q=>q.map(v=>v.toFixed(8)).join(','))).size,count);for(const q of nodes){near(s.field(...q,p),0,1e-9,id+' node on surface');s.grad(...q,p).forEach(v=>near(v,0,1e-9,id+' node gradient'));}}
for(let i=0;i<=50;i++){const theta=i*Math.PI/50;near(T6(Math.cos(theta)),Math.cos(6*theta),2e-14,'Chebyshev identity');}
for(const h of [-1,0,2,3,4])for(let i=0;i<12;i++){const theta=i*Math.PI/6,r=Math.sqrt(1+(h-2)**2/4);near(byId['translated-hyperboloid'].field(1+2*r*Math.cos(theta),-1+r*Math.sin(theta),h),0,1e-12,'translated hyperboloid trace');}
near(byId['translated-hyperboloid'].field(1,-1,2),-1,0,'translated center is inside waist');
const exactCases=[['sphere',0,p.a,1],['sphere',2,-p.a,1],['ellipsoid',0,p.a,1],['ellipsoid',1,p.b,1],['ellipsoid',2,p.c,1],['cone',2,0,1],['elliptic-paraboloid',2,0,1],['two-sheet',2,p.c,1],['transition',2,0,1]];
for(const [id,axis,h,count] of exactCases){const section=exactSlice(byId[id],p,axis,h,2.4);assert.equal(section?.points.length,count,id+' point section');for(const uv of section.points)near(byId[id].field(...slicePoint(axis,h,...uv),p),0,1e-12,id+' exact point');}
for(const [id,axis,h] of [['elliptic-cylinder',0,p.a],['elliptic-cylinder',1,p.b],['hyperbolic-cylinder',0,p.a],['parabolic-cylinder',1,0],['planes',0,0],['planes',1,0],...Array.from({length:3},(_,axis)=>['cayley',axis,1]),...Array.from({length:3},(_,axis)=>['cayley',axis,-1])]){const section=exactSlice(byId[id],p,axis,h,2.4);assert.equal(section?.segments.length,4,id+' line section');for(let i=0;i<section.segments.length;i+=2)near(byId[id].field(...slicePoint(axis,h,section.segments[i],section.segments[i+1]),p),0,2e-6,id+' exact line');}
assert.match(exactSlice(byId.sphere,p,2,1.6,2.4).note,/empty/);
const sphereMesh=makeMesh({id:'sphere',p:{...p,a:1},bound:1.3,n:30});let area=0,volume=0;
for(let i=0;i<sphereMesh.positions.length;i+=9){const a=Array.from(sphereMesh.positions.slice(i,i+3)),b=Array.from(sphereMesh.positions.slice(i+3,i+6)),c=Array.from(sphereMesh.positions.slice(i+6,i+9));const u=b.map((v,j)=>v-a[j]),v=c.map((v,j)=>v-a[j]),cross=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];area+=Math.hypot(...cross)/2;volume+=a.reduce((sum,v,j)=>sum+v*cross[j],0)/6;for(let k=0;k<3;k++){const q=Array.from(sphereMesh.positions.slice(i+3*k,i+3*k+3)),normal=Array.from(sphereMesh.normals.slice(i+3*k,i+3*k+3));near(Math.hypot(...q),1,2e-6,'sphere vertex');near(Math.hypot(...normal),1,1e-6,'unit normal');assert.ok(normal.reduce((s,v,j)=>s+v*cross[j],0)>=-1e-8,'outward winding');}}
near(area/(4*Math.PI),1,.003,'sphere mesh area');near(volume/(4*Math.PI/3),1,.004,'sphere mesh volume');
for(const id of ['kummer','barth','chebyshev']){const s=byId[id],mesh=makeMesh({id,p,bound:s.bound,n:24});assert.ok(mesh.triangles>100,id+' has a mesh');let residual=0;for(let i=0;i<mesh.positions.length;i+=3){const q=Array.from(mesh.positions.slice(i,i+3));q.forEach(v=>assert.ok(Number.isFinite(v)&&Math.abs(v)<=s.bound+1e-6));const g=s.grad(...q,p);residual=Math.max(residual,Math.abs(s.field(...q,p))/(1+Math.hypot(...g)));}assert.ok(residual<.00005,`${id}: mesh residual ${residual}`);}
const section=makeSlice(byId.sphere,{...p,a:1},2,.6,1.2,100);for(let i=0;i<section.length;i+=2)near(Math.hypot(section[i],section[i+1]),.8,.002,'circle trace');
console.log(`Surface mathematics: ${checks.toLocaleString()} numerical checks passed. ${surfaces.length} surfaces; 106 gallery nodes; exact degenerate traces; translated hyperboloid; sphere area/volume; mesh residuals.`);
