/* npm install playwright; CHROME_PATH=/path/to/chrome node tests/browser.cjs [URL]
 * Tests offline by default. Set SCREENSHOT_DIR to retain screenshots.
 */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.argv[2]||'file://'+path.resolve(__dirname,'../index.html');
const shotDir=process.env.SCREENSHOT_DIR;
const scenes=['overview','permutations','designs','orders','sylow','triangles','codes','representations','methods'];
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function scene(id,n=11){await page.goto(base+'#'+id+'?group='+n);await page.waitForFunction(([id,n])=>document.querySelector('nav a[aria-current]')?.getAttribute('href')===`#${id}?group=${n}`,[id,n]);await page.waitForTimeout(30);assert.ok((await page.locator('h1').textContent()).length>4);assert.equal(await page.locator('#group-select').inputValue(),String(n));}
 for(const n of [11,12,22,23,24])for(const id of scenes){await scene(id,n);assert.equal(await page.locator('body').evaluate(b=>b.scrollWidth<=innerWidth+1),true,`desktop overflow ${id}/${n}`);}
 await scene('permutations');await page.locator('#word-input').fill('r i^-1 j^2');await page.locator('#evaluate-word').click();assert.match(await page.locator('#word-result').textContent(),/element order/);await page.locator('#step-word').click();await page.locator('#simplicity-check').click();assert.match(await page.locator('#simplicity-result').textContent(),/Verified/);await page.locator('#word-input').fill('bad');await page.locator('#evaluate-word').click();assert.match(await page.locator('#word-result').textContent(),/Unknown generator/);
 for(const n of [11,12,22,23,24]){await scene('designs',n);await page.locator('#example-subset').click();assert.match(await page.locator('#completion').textContent(),/Unique completion/);await page.locator('#audit-design').click();assert.match(await page.locator('#audit-result').textContent(),/Verified/);await page.locator('#orbit-all').click();assert.match(await page.locator('#orbit-status').textContent(),/orbit is complete/);if(n===11){await page.locator('#rigidity-check').click();assert.match(await page.locator('#rigidity-result').textContent(),/720 candidates tested; 1 survives/);await page.locator('#biplane-mode').click();await page.locator('#example-subset').click();assert.match(await page.locator('#completion').textContent(),/Two translates/);}if(n===12){await page.locator('#projective-check').click();assert.match(await page.locator('#projective-result').textContent(),/Verified/);}}
 for(const n of [11,12,22,23,24]){await scene('orders',n);await page.locator('#sift-odd').click();assert.match(await page.locator('#sift-result').textContent(),/Not a member/);await page.locator('#audit-chain').click();assert.match(await page.locator('#chain-audit').textContent(),/Verified/);await page.locator('[data-level]').last().click();assert.equal(await page.locator('#chain-next').isDisabled(),true);await scene('sylow',n);const rows=page.locator('#sylow-table tr[data-select]');for(let i=0;i<await rows.count();i++){await rows.nth(i).click();assert.doesNotMatch(await page.locator('#normalizer-explanation').textContent(),/failed/);}}
 for(const n of [11,12]){
  await page.goto(base+'#orders?group='+n+'&subgroup=q8');await page.waitForSelector('#q8-witness');
  assert.equal(await page.locator('[data-level].active').getAttribute('data-level'),String(n===12?4:3));
  assert.match(await page.locator('#chain-title').textContent(),n===12?/After fixing ∞, 0, 1, 2/:/After fixing 0, 1, 2/);
  assert.equal(await page.locator('#q8-table tbody tr').count(),8);
  assert.deepEqual(await page.locator('#q8-table tbody tr td:nth-child(2)').allTextContents(),['3','4','5','10','6','8','9','7']);
  await page.locator('#q8-check').click();assert.match(await page.locator('#q8-result').textContent(),/Verified: K = ⟨i,j⟩ ≅ Q₈/);assert.doesNotMatch(await page.locator('#q8-result').textContent(),/failed/i);
  await page.locator('#q8-element').selectOption('2');assert.match(await page.locator('#q8-action').textContent(),/i²: 3 → 5; element order 2/);
  await page.locator('#q8-chain').click();assert.equal(await page.locator('#chain-next').isDisabled(),true);
 }
 await scene('codes');for(const name of ['ternary11','ternary12','binary23','binary24']){await page.locator('#code-select').selectOption(name);await page.locator('#inject-errors').click();await page.locator('#decode').click();assert.match(await page.locator('#decode-result').textContent(),/Recovered the sent word/);await page.locator('#too-many-errors').click();await page.locator('#decode').click();assert.match(await page.locator('#decode-result').textContent(),/not the sent word|Ambiguous/);await page.locator('#code-supports').click();assert.match(await page.locator('#support-result').textContent(),/Verified/);}
 await scene('representations');await page.locator('#module-check').click();assert.match(await page.locator('#module-result').textContent(),/yes, no, no/);await page.locator('#invariant-check').click();assert.match(await page.locator('#invariant-result').textContent(),/Verified/);
 await scene('methods');await page.locator('#run-audit').click();assert.match(await page.locator('#all-audit').textContent(),/All checks passed/);
 if(shotDir){fs.mkdirSync(shotDir,{recursive:true});for(const [id,n] of [['overview',11],['designs',24],['orders',24],['codes',11],['sylow',24]]){await scene(id,n);await page.screenshot({path:path.join(shotDir,id+'-'+n+'.png'),fullPage:true});}await page.goto(base+'#orders?group=12&subgroup=q8');await page.waitForSelector('#q8-witness');await page.locator('#q8-check').click();await page.locator('#q8-witness').screenshot({path:path.join(shotDir,'q8-stabilizer-12.png')});}
 await page.setViewportSize({width:390,height:844});for(const id of scenes){await scene(id,24);assert.equal(await page.locator('body').evaluate(b=>b.scrollWidth<=innerWidth+1),true,`mobile overflow ${id}`);}if(shotDir)await page.screenshot({path:path.join(shotDir,'mobile-methods.png'),fullPage:true});
 await page.goto(base+'#orders?group=12&subgroup=q8');await page.waitForSelector('#q8-witness');await page.locator('#q8-check').click();assert.match(await page.locator('#q8-result').textContent(),/Verified/);assert.equal(await page.locator('body').evaluate(b=>b.scrollWidth<=innerWidth+1),true,'mobile quaternion certificate overflow');if(shotDir)await page.locator('#q8-witness').screenshot({path:path.join(shotDir,'mobile-q8-stabilizer.png')});
 await scene('overview');await page.locator('#present').click();assert.equal(await page.locator('body').evaluate(b=>b.classList.contains('present-mode')),true);await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>location.hash.startsWith('#permutations'));await page.locator('#present').click();
 assert.deepEqual(errors,[],'browser console errors');await browser.close();console.log(JSON.stringify({passed:true,groups:5,chapters:9,desktop:'1440x1000',mobile:'390x844',offline:base.startsWith('file:'),errors},null,2));
})().catch(e=>{console.error(e);process.exit(1);});
